/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 150 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 203 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef unsigned long u_int64_t;
#line 196 "../stdio.h"
typedef unsigned int u_int___0;
#line 200 "../stdio.h"
typedef int int32_t___0;
#line 203 "../stdio.h"
typedef unsigned int u_int32_t___0;
#line 207 "../stdio.h"
typedef unsigned char u_char___0;
#line 351 "../openssh.h"
struct sshbuf {
   u_char___0 *d ;
   u_char___0 const   *cd ;
   size_t off ;
   size_t size ;
   size_t max_size ;
   size_t alloc ;
   int readonly ;
   int dont_free ;
   u_int___0 refcount ;
   struct sshbuf *parent ;
};
#line 364 "../openssh.h"
typedef u_int___0 BN_ULONG;
#line 372 "../openssh.h"
struct bignum_st {
   BN_ULONG *d ;
   int top ;
   int dmax ;
   int neg ;
   int flags ;
};
#line 390 "../openssh.h"
typedef struct bignum_st BIGNUM;
#line 391 "../openssh.h"
struct rsa_st {
   int pad ;
   int32_t___0 version ;
   void const   *meth ;
   void *engine ;
   BIGNUM *n ;
   BIGNUM *e ;
   BIGNUM *d ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *dmp1 ;
   BIGNUM *dmq1 ;
   BIGNUM *iqmp ;
   void *pss ;
   int ex_data ;
   int references ;
   int flags ;
   void *_method_mod_n ;
   void *_method_mod_p ;
   void *_method_mod_q ;
   char *bignum_data ;
   void *blinding ;
   void *mt_blinding ;
   void *lock ;
};
#line 391 "../openssh.h"
typedef struct rsa_st RSA;
#line 434 "../openssh.h"
struct dsa_st {
   int pad ;
   int32_t___0 version ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *g ;
   BIGNUM *pub_key ;
   BIGNUM *priv_key ;
   int flags ;
};
#line 434 "../openssh.h"
typedef struct dsa_st DSA;
#line 621
struct sshkey;
#line 699 "../openssh.h"
struct sshkey_cert {
   struct sshbuf *certblob ;
   u_int___0 type ;
   u_int64_t serial ;
   char *key_id ;
   u_int___0 nprincipals ;
   char **principals ;
   u_int64_t valid_after ;
   u_int64_t valid_before ;
   struct sshbuf *critical ;
   struct sshbuf *extensions ;
   struct sshkey *signature_key ;
};
#line 713 "../openssh.h"
struct sshkey {
   int type ;
   int flags ;
   RSA *rsa ;
   DSA *dsa ;
   int ecdsa_nid ;
   void *ecdsa ;
   u_char___0 *ed25519_sk ;
   u_char___0 *ed25519_pk ;
   struct sshkey_cert *cert ;
};
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 242
extern int fflush(FILE *__stream ) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 376 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) srand)(unsigned int __seed ) ;
#line 466
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 468
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) calloc)(size_t __nmemb ,
                                                                               size_t __size )  __attribute__((__malloc__)) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 28 "openssh_leak_6.c"
int sshkey_type_plain(int type ) 
{ 


  {
#line 31
  switch (type) {
  case 5: 
  case 9: 
#line 34
  return (1);
  case 6: 
  case 10: 
#line 37
  return (2);
  case 7: 
#line 39
  return (3);
  case 8: 
#line 41
  return (4);
  default: 
#line 43
  return (type);
  }
}
}
#line 47 "openssh_leak_6.c"
size_t sshbuf_len(struct sshbuf  const  *buf ) 
{ 


  {
#line 50
  return ((size_t )(buf->size - buf->off));
}
}
#line 53 "openssh_leak_6.c"
u_char___0 const   *sshbuf_ptr(struct sshbuf  const  *buf ) 
{ 


  {
#line 56
  return ((u_char___0 const   *)(buf->cd + buf->off));
}
}
#line 59 "openssh_leak_6.c"
struct sshbuf *sshbuf_from(void const   *blob , size_t len ) 
{ 
  struct sshbuf *ret ;
  void *tmp ;
  size_t tmp___0 ;
  size_t tmp___1 ;

  {
#line 64
  if ((unsigned long )blob == (unsigned long )((void *)0)) {
#line 66
    return ((struct sshbuf *)((void *)0));
  } else
#line 64
  if (len > 134217728UL) {
#line 66
    return ((struct sshbuf *)((void *)0));
  } else {
#line 64
    tmp = calloc(sizeof(*ret), (size_t )1);
#line 64
    ret = (struct sshbuf *)tmp;
#line 64
    if ((unsigned long )ret == (unsigned long )((void *)0)) {
#line 66
      return ((struct sshbuf *)((void *)0));
    }
  }
#line 67
  tmp___1 = len;
#line 67
  ret->max_size = tmp___1;
#line 67
  tmp___0 = tmp___1;
#line 67
  ret->size = tmp___0;
#line 67
  ret->alloc = tmp___0;
#line 68
  ret->readonly = 1;
#line 69
  ret->refcount = (u_int___0 )1;
#line 70
  ret->parent = (struct sshbuf *)((void *)0);
#line 71
  ret->cd = (u_char___0 const   *)blob;
#line 72
  ret->d = (u_char___0 *)((void *)0);
#line 73
  return (ret);
}
}
#line 87
int sshbuf_peek_string_direct(struct sshbuf  const  *buf , u_char___0 const   **valp ,
                              size_t *lenp ) ;
#line 76 "openssh_leak_6.c"
int sshbuf_get_string_direct(struct sshbuf *buf , u_char___0 const   **valp , size_t *lenp ) 
{ 
  size_t len ;
  u_char___0 const   *p ;
  int r ;

  {
#line 83
  if ((unsigned long )valp != (unsigned long )((void *)0)) {
#line 84
    *valp = (u_char___0 const   *)((void *)0);
  }
#line 85
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 86
    *lenp = (size_t )0;
  }
#line 87
  r = sshbuf_peek_string_direct(buf, & p, & len);
#line 87
  if (r < 0) {
#line 88
    return (r);
  }
#line 89
  if ((unsigned long )valp != (unsigned long )((u_char___0 const   **)0)) {
#line 90
    *valp = p;
  }
#line 91
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 92
    *lenp = len;
  }
#line 93
  return (0);
}
}
#line 96 "openssh_leak_6.c"
int sshbuf_peek_string_direct(struct sshbuf  const  *buf , u_char___0 const   **valp ,
                              size_t *lenp ) 
{ 
  u_int32_t___0 len ;
  u_char___0 const   *p ;
  u_char___0 const   *tmp ;
  size_t tmp___0 ;

  {
#line 101
  tmp = sshbuf_ptr(buf);
#line 101
  p = tmp;
#line 103
  if ((unsigned long )valp != (unsigned long )((void *)0)) {
#line 104
    *valp = (u_char___0 const   *)((void *)0);
  }
#line 105
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 106
    *lenp = (size_t )0;
  }
#line 107
  tmp___0 = sshbuf_len(buf);
#line 107
  if (tmp___0 < 4UL) {
#line 108
    while (1) {
#line 108
      printf((char const   * __restrict  )"%s:%d %s: ", "openssh_leak_6.c", 108, "sshbuf_peek_string_direct");
#line 108
      printf((char const   * __restrict  )"SSH_ERR_MESSAGE_INCOMPLETE");
#line 108
      printf((char const   * __restrict  )"\n");
#line 108
      fflush(stdout);
#line 108
      break;
    }
#line 109
    return (-3);
  }
#line 111
  len = (u_int32_t___0 )15;
#line 112
  if (len > 134217724U) {
#line 113
    while (1) {
#line 113
      printf((char const   * __restrict  )"%s:%d %s: ", "openssh_leak_6.c", 113, "sshbuf_peek_string_direct");
#line 113
      printf((char const   * __restrict  )"SSH_ERR_STRING_TOO_LARGE");
#line 113
      printf((char const   * __restrict  )"\n");
#line 113
      fflush(stdout);
#line 113
      break;
    }
#line 114
    return (-6);
  }
#line 116
  if ((unsigned long )valp != (unsigned long )((u_char___0 const   **)0)) {
#line 117
    *valp = p + 4;
  }
#line 118
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 119
    *lenp = (size_t )len;
  }
#line 120
  return (0);
}
}
#line 144
extern int ( /* missing proto */  memcpy)() ;
#line 123 "openssh_leak_6.c"
int sshbuf_get_cstring(struct sshbuf *buf , char **valp , size_t *lenp ) 
{ 
  size_t len ;
  u_char___0 const   *p ;
  int r ;
  char *tmp ;
  void *tmp___0 ;

  {
#line 130
  if ((unsigned long )valp != (unsigned long )((void *)0)) {
#line 131
    *valp = (char *)((void *)0);
  }
#line 132
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 133
    *lenp = (size_t )0;
  }
#line 134
  r = sshbuf_peek_string_direct((struct sshbuf  const  *)buf, & p, & len);
#line 134
  if (r != 0) {
#line 135
    return (r);
  }
#line 137
  r = sshbuf_get_string_direct(buf, (u_char___0 const   **)((void *)0), (size_t *)((void *)0));
#line 137
  if (r != 0) {
#line 138
    return (-1);
  }
#line 139
  if ((unsigned long )valp != (unsigned long )((void *)0)) {
#line 140
    tmp___0 = malloc(len + 1UL);
#line 140
    tmp = (char *)tmp___0;
#line 140
    *valp = tmp;
#line 140
    if ((unsigned long )tmp == (unsigned long )((void *)0)) {
#line 141
      while (1) {
#line 141
        printf((char const   * __restrict  )"%s:%d %s: ", "openssh_leak_6.c", 141,
               "sshbuf_get_cstring");
#line 141
        printf((char const   * __restrict  )"SSH_ERR_ALLOC_FAIL");
#line 141
        printf((char const   * __restrict  )"\n");
#line 141
        fflush(stdout);
#line 141
        break;
      }
#line 142
      return (-2);
    }
#line 144
    memcpy(*valp, p, len);
#line 145
    *(*valp + len) = (char )'\000';
  }
#line 147
  if ((unsigned long )lenp != (unsigned long )((void *)0)) {
#line 148
    *lenp = len;
  }
#line 149
  return (0);
}
}
#line 170
extern int ( /* missing proto */  strcmp)() ;
#line 152 "openssh_leak_6.c"
int ssh_ed25519_verify(struct sshkey  const  *key , u_char___0 const   *signature ,
                       size_t signaturelen , u_char___0 const   *data , size_t datalen ) 
{ 
  struct sshbuf *b ;
  char *ktype ;
  u_char___0 const   *sigblob ;
  u_char___0 *sm ;
  u_char___0 *m ;
  size_t len ;
  unsigned long long smlen ;
  unsigned long long mlen ;
  int r ;
  int tmp ;

  {
#line 157
  b = (struct sshbuf *)((void *)0);
#line 158
  ktype = (char *)((void *)0);
#line 160
  sm = (u_char___0 *)((void *)0);
#line 160
  m = (u_char___0 *)((void *)0);
#line 162
  smlen = 0ULL;
#line 162
  mlen = 0ULL;
#line 165
  b = sshbuf_from((void const   *)signature, signaturelen);
#line 165
  if ((unsigned long )b == (unsigned long )((void *)0)) {
#line 166
    return (-2);
  }
#line 167
  r = sshbuf_get_cstring(b, & ktype, (size_t *)((void *)0));
#line 167
  if (r != 0) {
#line 169
    goto out;
  } else {
#line 167
    r = sshbuf_get_string_direct(b, & sigblob, & len);
#line 167
    if (r != 0) {
#line 169
      goto out;
    }
  }
#line 170
  tmp = strcmp("ssh-ed25519", ktype);
#line 170
  if (tmp != 0) {
#line 171
    r = -13;
#line 172
    goto out;
  }
#line 175
  if (len > 64UL) {
#line 176
    r = -4;
#line 177
    goto out;
  }
#line 179
  if (datalen >= 15UL - len) {
#line 180
    return (-10);
  }
#line 184
  r = 0;
  out: 
#line 186
  free((void *)b);
#line 187
  free((void *)ktype);
#line 188
  return (r);
}
}
#line 196
extern int ( /* missing proto */  strlen)() ;
#line 198
extern int ( /* missing proto */  time)() ;
#line 191 "openssh_leak_6.c"
int main(int argc , char **argv ) 
{ 
  struct sshkey key ;
  char *sign ;
  char *data ;
  size_t siglen ;
  int tmp ;
  size_t datalen ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 194
  sign = (char *)"key:ssh-ed25519";
#line 196
  tmp = strlen(sign);
#line 196
  siglen = (size_t )tmp;
#line 198
  tmp___0 = time((void *)0);
#line 198
  srand((unsigned int )tmp___0);
#line 200
  if (argc == 1) {
#line 201
    printf((char const   * __restrict  )"no data %s\n", *(argv + 0));
#line 201
    exit(1);
  }
#line 202
  data = *(argv + 1);
#line 203
  tmp___1 = strlen(data);
#line 203
  datalen = (size_t )tmp___1;
#line 204
  ssh_ed25519_verify((struct sshkey  const  *)(& key), (u_char___0 const   *)sign,
                     siglen, (u_char___0 const   *)data, datalen);
#line 205
  return (0);
}
}
