/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 124 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
#line 125 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
#line 126 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
#line 127 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
#line 129 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 130 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 46 "/usr/include/x86_64-linux-gnu/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   __syscall_slong_t __glibc_reserved[3] ;
};
#line 29 "../include/common.h"
typedef int bool;
#line 34 "../include/common.h"
typedef void make_cleanup_ftype(void * );
#line 36 "../include/common.h"
struct cleanup {
   struct cleanup *next ;
   void (*function)(void * ) ;
   void (*free_arg)(void * ) ;
   void *arg ;
};
#line 519 "../include/binutils.h"
typedef int bfd_boolean;
#line 524
struct bfd;
#line 17 "../include/bfd.h"
typedef int bool___0;
#line 21
enum bfd_flavour {
    bfd_target_unknown_flavour = 0,
    bfd_target_aout_flavour = 1,
    bfd_target_coff_flavour = 2,
    bfd_target_ecoff_flavour = 3,
    bfd_target_xcoff_flavour = 4,
    bfd_target_elf_flavour = 5,
    bfd_target_ieee_flavour = 6,
    bfd_target_nlm_flavour = 7,
    bfd_target_oasys_flavour = 8,
    bfd_target_tekhex_flavour = 9,
    bfd_target_srec_flavour = 10,
    bfd_target_verilog_flavour = 11,
    bfd_target_ihex_flavour = 12,
    bfd_target_som_flavour = 13,
    bfd_target_os9k_flavour = 14,
    bfd_target_versados_flavour = 15,
    bfd_target_msdos_flavour = 16,
    bfd_target_ovax_flavour = 17,
    bfd_target_evax_flavour = 18,
    bfd_target_mmo_flavour = 19,
    bfd_target_mach_o_flavour = 20,
    bfd_target_pef_flavour = 21,
    bfd_target_pef_xlib_flavour = 22,
    bfd_target_sym_flavour = 23
} ;
#line 50 "../include/bfd.h"
struct bfd_target {
   char *name ;
   enum bfd_flavour flavour ;
};
#line 57 "../include/bfd.h"
struct bfd {
   char *filename ;
   int direction ;
   struct bfd *archive_next ;
   struct bfd_target  const  *xvec ;
   void *memory ;
   bool___0 cacheable ;
};
#line 69 "../include/bfd.h"
typedef struct bfd bfd___0;
#line 180 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) rename)(char const   *__old ,
                                                                             char const   *__new ) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 374 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) rand)(void) ;
#line 466
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 619
extern int ( __attribute__((__nonnull__(1))) mkstemp)(char *__template ) ;
#line 262 "/usr/include/x86_64-linux-gnu/sys/stat.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) lstat)(char const   * __restrict  __file ,
                                                                                              struct stat * __restrict  __buf ) ;
#line 283
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) chmod)(char const   *__file ,
                                                                                            __mode_t __mode ) ;
#line 31 "../include/common.h"
bool true  =    1;
#line 32 "../include/common.h"
bool false  =    0;
#line 44 "../include/common.h"
static struct cleanup  const  sentinel_cleanup  =    {(struct cleanup *)0, (void (*)(void * ))0, (void (*)(void * ))0, (void *)0};
#line 49 "../include/common.h"
static struct cleanup *cleanup_chain  =    (struct cleanup *)(& sentinel_cleanup);
#line 50 "../include/common.h"
static struct cleanup *final_cleanup_chain  ;
#line 52
void discard_cleanups(struct cleanup *old_chain ) ;
#line 53
void discard_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) ;
#line 55
void discard_final_cleanups(struct cleanup *old_chain ) ;
#line 56
static void do_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) ;
#line 58
void do_cleanups(struct cleanup *old_chain ) ;
#line 59
static struct cleanup *make_my_cleanup2(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                        void *arg , void (*free_arg)(void * ) ) ;
#line 62
static struct cleanup *make_my_cleanup(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                       void *arg ) ;
#line 65
struct cleanup *make_cleanup(make_cleanup_ftype *function , void *arg ) ;
#line 68 "../include/common.h"
void discard_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 71
  discard_my_cleanups(& cleanup_chain, old_chain);
#line 72
  return;
}
}
#line 74 "../include/common.h"
void discard_final_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 77
  discard_my_cleanups(& final_cleanup_chain, old_chain);
#line 78
  return;
}
}
#line 80 "../include/common.h"
void discard_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) 
{ 
  struct cleanup *ptr ;

  {
#line 86
  while (1) {
#line 86
    ptr = *pmy_chain;
#line 86
    if (! ((unsigned long )ptr != (unsigned long )old_chain)) {
#line 86
      break;
    }
#line 88
    *pmy_chain = ptr->next;
#line 89
    if (ptr->free_arg) {
#line 90
      (*(ptr->free_arg))(ptr->arg);
    }
#line 91
    free((void *)ptr);
  }
#line 94
  printf((char const   * __restrict  )"freearg: %x\n", ptr->arg);
#line 95
  return;
}
}
#line 97 "../include/common.h"
static void do_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) 
{ 
  struct cleanup *ptr ;

  {
#line 103
  while (1) {
#line 103
    ptr = *pmy_chain;
#line 103
    if (! ((unsigned long )ptr != (unsigned long )old_chain)) {
#line 103
      break;
    }
#line 105
    *pmy_chain = ptr->next;
#line 106
    (*(ptr->function))(ptr->arg);
#line 107
    printf((char const   * __restrict  )"cleanup!!!!! =========\n");
#line 108
    printf((char const   * __restrict  )"%x\n", ptr->arg);
#line 109
    if (ptr->free_arg) {
#line 110
      (*(ptr->free_arg))(ptr->arg);
    }
#line 112
    free((void *)ptr);
  }
#line 114
  return;
}
}
#line 116 "../include/common.h"
void do_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 118
  do_my_cleanups(& cleanup_chain, old_chain);
#line 119
  return;
}
}
#line 121 "../include/common.h"
static struct cleanup *make_my_cleanup2(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                        void *arg , void (*free_arg)(void * ) ) 
{ 
  struct cleanup *new ;
  void *tmp ;
  struct cleanup *old_chain ;

  {
#line 125
  tmp = malloc(sizeof(struct cleanup ));
#line 125
  new = (struct cleanup *)tmp;
#line 127
  old_chain = *pmy_chain;
#line 129
  new->next = *pmy_chain;
#line 130
  new->function = function;
#line 131
  new->free_arg = free_arg;
#line 132
  new->arg = arg;
#line 133
  *pmy_chain = new;
#line 135
  if ((unsigned long )old_chain == (unsigned long )((void *)0)) {
#line 136
    exit(1);
  }
#line 138
  return (old_chain);
}
}
#line 141 "../include/common.h"
static struct cleanup *make_my_cleanup(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                       void *arg ) 
{ 
  struct cleanup *tmp ;

  {
#line 145
  tmp = make_my_cleanup2(pmy_chain, function, arg, (void (*)(void * ))((void *)0));
#line 145
  return (tmp);
}
}
#line 148 "../include/common.h"
struct cleanup *make_cleanup(make_cleanup_ftype *function , void *arg ) 
{ 
  struct cleanup *tmp ;

  {
#line 151
  tmp = make_my_cleanup(& cleanup_chain, function, arg);
#line 151
  return (tmp);
}
}
#line 35 "binutils_leak_2.c"
char const   *output_filename  =    "a.out";
#line 45
extern int ( /* missing proto */  strrchr)() ;
#line 53
extern int ( /* missing proto */  memcpy)() ;
#line 41 "binutils_leak_2.c"
static char *template_in_dir(char const   *path ) 
{ 
  char const   *slash ;
  int tmp ;
  char *tmpname ;
  size_t len ;
  void *tmp___0 ;
  size_t tmp___1 ;
  void *tmp___2 ;

  {
#line 45
  tmp = strrchr(path, '/');
#line 45
  slash = (char const   *)tmp;
#line 49
  if ((unsigned long )slash != (unsigned long )((char *)((void *)0))) {
#line 51
    len = (size_t )(slash - path);
#line 52
    tmp___0 = malloc((len + sizeof("stXXXXXX")) + 2UL);
#line 52
    tmpname = (char *)tmp___0;
#line 53
    memcpy(tmpname, path, len);
#line 54
    tmp___1 = len;
#line 54
    len ++;
#line 54
    *(tmpname + tmp___1) = (char )'/';
  } else {
#line 58
    tmp___2 = malloc(sizeof("stXXXXXX"));
#line 58
    tmpname = (char *)tmp___2;
#line 59
    len = (size_t )0;
  }
#line 62
  memcpy(tmpname + len, "stXXXXXX", sizeof("stXXXXXX"));
#line 63
  return (tmpname);
}
}
#line 81
extern int ( /* missing proto */  close)() ;
#line 69 "binutils_leak_2.c"
char *make_tempname(char *filename ) 
{ 
  char *tmpname ;
  char *tmp ;
  int fd ;

  {
#line 72
  tmp = template_in_dir((char const   *)filename);
#line 72
  tmpname = tmp;
#line 75
  fd = mkstemp(tmpname);
#line 76
  if (fd == -1) {
#line 78
    free((void *)tmpname);
#line 79
    return ((char *)((void *)0));
  }
#line 81
  close(fd);
#line 82
  return (tmpname);
}
}
#line 103
extern int ( /* missing proto */  utime)() ;
#line 85 "binutils_leak_2.c"
void set_times(char const   *destination , struct stat  const  *statbuf ) 
{ 
  int result ;
  long tb[2] ;

  {
#line 101
  tb[0] = (long )statbuf->st_atim.tv_sec;
#line 102
  tb[1] = (long )statbuf->st_mtim.tv_sec;
#line 103
  result = utime(destination, tb);
#line 116
  if (result != 0) {
#line 117
    printf((char const   * __restrict  )"%s: cannot set time:", destination);
  }
#line 118
  return;
}
}
#line 156
extern int ( /* missing proto */  chown)() ;
#line 164
extern int ( /* missing proto */  unlink)() ;
#line 120 "binutils_leak_2.c"
int smart_rename(char const   *from , char const   *to , int preserve_dates ) 
{ 
  bfd_boolean exists ;
  struct stat s ;
  int ret ;
  int tmp ;
  int tmp___0 ;

  {
#line 125
  ret = 0;
#line 127
  tmp = lstat((char const   * __restrict  )to, (struct stat * __restrict  )(& s));
#line 127
  exists = tmp == 0;
#line 131
  if (! exists) {
#line 131
    goto _L;
  } else
#line 131
  if (! ((s.st_mode & 61440U) == 40960U)) {
#line 131
    if ((s.st_mode & 61440U) == 32768U) {
#line 131
      if (s.st_mode & 128U) {
#line 131
        if (s.st_nlink == 1UL) {
          _L: /* CIL Label */ 
#line 138
          ret = rename(from, to);
#line 139
          if (ret == 0) {
#line 141
            if (exists) {
#line 155
              chmod(to, s.st_mode & 511U);
#line 156
              tmp___0 = chown(to, s.st_uid, s.st_gid);
#line 156
              if (tmp___0 >= 0) {
#line 157
                chmod(to, s.st_mode & 4095U);
              }
            }
          } else {
#line 163
            printf((char const   * __restrict  )"unable to rename \'%s\';", to);
#line 164
            unlink(from);
          }
        } else {
#line 131
          goto _L___2;
        }
      } else {
#line 131
        goto _L___2;
      }
    } else {
#line 131
      goto _L___2;
    }
  } else {
    _L___2: /* CIL Label */ 
#line 169
    if (ret != 0) {
#line 170
      printf((char const   * __restrict  )"unable to copy file \'%s\';", to);
    }
#line 172
    if (preserve_dates) {
#line 173
      set_times(to, (struct stat  const  *)(& s));
    }
#line 174
    unlink(from);
  }
#line 177
  return (ret);
}
}
#line 180 "binutils_leak_2.c"
void unlink_if_ordinary(char const   *name ) 
{ 


  {
#line 182
  printf((char const   * __restrict  )"%d\n", *((int *)name));
#line 183
  return;
}
}
#line 185 "binutils_leak_2.c"
bfd___0 *bfd_openw(char const   *name ) 
{ 
  bfd___0 *nbfd ;
  void *tmp ;

  {
#line 187
  printf((char const   * __restrict  )"%d\n", *((int *)name));
#line 189
  tmp = malloc(sizeof(bfd___0 ));
#line 189
  nbfd = (bfd___0 *)tmp;
#line 190
  return (nbfd);
}
}
#line 193 "binutils_leak_2.c"
bfd_boolean *bfd_close(bfd___0 *abfd ) 
{ 
  bfd_boolean ret ;
  int tmp___0 ;

  {
#line 196
  tmp___0 = rand();
#line 196
  if (tmp___0 % 2 == 1) {
#line 196
    ret = 1;
  } else {
#line 196
    ret = 0;
  }
#line 198
  free((void *)abfd);
#line 199
  return ((bfd_boolean *)0);
}
}
#line 201 "binutils_leak_2.c"
char *bfd_get_filename(bfd___0 *iarch ) 
{ 


  {
#line 203
  return (iarch->filename);
}
}
#line 213
extern int ( /* missing proto */  strlen)() ;
#line 214
extern int ( /* missing proto */  strcpy)() ;
#line 206 "binutils_leak_2.c"
static void write_archive(bfd___0 *iarch ) 
{ 
  bfd___0 *obfd ;
  char *old_name ;
  char *new_name ;
  bfd___0 *contents_head ;
  char *tmp ;
  int tmp___0 ;
  void *tmp___1 ;
  char *tmp___2 ;
  bfd_boolean *tmp___3 ;
  int tmp___4 ;

  {
#line 211
  contents_head = iarch->archive_next;
#line 213
  tmp = bfd_get_filename(iarch);
#line 213
  tmp___0 = strlen(tmp);
#line 213
  tmp___1 = malloc((size_t )(tmp___0 + 1));
#line 213
  old_name = (char *)tmp___1;
#line 214
  tmp___2 = bfd_get_filename(iarch);
#line 214
  strcpy(old_name, tmp___2);
#line 215
  new_name = make_tempname(old_name);
#line 217
  if ((unsigned long )new_name == (unsigned long )((void *)0)) {
#line 218
    printf((char const   * __restrict  )"could not create temporary file whilst writing archive%s",
           "");
#line 218
    exit(1);
  }
#line 220
  output_filename = (char const   *)new_name;
#line 222
  obfd = bfd_openw((char const   *)new_name);
#line 224
  if ((unsigned long )obfd == (unsigned long )((void *)0)) {
#line 225
    printf((char const   * __restrict  )"%s", old_name);
#line 225
    exit(1);
  }
#line 227
  tmp___3 = bfd_close(obfd);
#line 227
  if (! tmp___3) {
#line 228
    printf((char const   * __restrict  )"%s", old_name);
#line 228
    exit(1);
  }
#line 230
  output_filename = (char const   *)((void *)0);
#line 233
  bfd_close(iarch);
#line 235
  tmp___4 = smart_rename((char const   *)new_name, (char const   *)old_name, 0);
#line 235
  if (tmp___4 != 0) {
#line 236
    exit(1);
  }
#line 237
  free((void *)old_name);
#line 239
  return;
}
}
#line 241 "binutils_leak_2.c"
int main(void) 
{ 
  bfd___0 iarch ;

  {
#line 244
  write_archive(& iarch);
#line 245
  return (0);
}
}
