/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 129 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 70 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef __mode_t mode_t;
#line 75 "/usr/include/time.h"
typedef __time_t time_t;
#line 197 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef long int64_t;
#line 203 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef unsigned long u_int64_t;
#line 196 "../stdio.h"
typedef unsigned int u_int___0;
#line 200 "../stdio.h"
typedef int int32_t___0;
#line 203 "../stdio.h"
typedef unsigned int u_int32_t___0;
#line 207 "../stdio.h"
typedef unsigned char u_char___0;
#line 214 "../stdio.h"
typedef int sig_atomic_t;
#line 351 "../openssh.h"
struct sshbuf {
   u_char___0 *d ;
   u_char___0 const   *cd ;
   size_t off ;
   size_t size ;
   size_t max_size ;
   size_t alloc ;
   int readonly ;
   int dont_free ;
   u_int___0 refcount ;
   struct sshbuf *parent ;
};
#line 364 "../openssh.h"
typedef u_int___0 BN_ULONG;
#line 372 "../openssh.h"
struct bignum_st {
   BN_ULONG *d ;
   int top ;
   int dmax ;
   int neg ;
   int flags ;
};
#line 390 "../openssh.h"
typedef struct bignum_st BIGNUM;
#line 391 "../openssh.h"
struct rsa_st {
   int pad ;
   int32_t___0 version ;
   void const   *meth ;
   void *engine ;
   BIGNUM *n ;
   BIGNUM *e ;
   BIGNUM *d ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *dmp1 ;
   BIGNUM *dmq1 ;
   BIGNUM *iqmp ;
   void *pss ;
   int ex_data ;
   int references ;
   int flags ;
   void *_method_mod_n ;
   void *_method_mod_p ;
   void *_method_mod_q ;
   char *bignum_data ;
   void *blinding ;
   void *mt_blinding ;
   void *lock ;
};
#line 391 "../openssh.h"
typedef struct rsa_st RSA;
#line 434 "../openssh.h"
struct dsa_st {
   int pad ;
   int32_t___0 version ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *g ;
   BIGNUM *pub_key ;
   BIGNUM *priv_key ;
   int flags ;
};
#line 434 "../openssh.h"
typedef struct dsa_st DSA;
#line 615 "../openssh.h"
struct newkeys {
   char *enc ;
   char *mac ;
   char *comp ;
};
#line 626
struct sshkey;
#line 626 "../openssh.h"
struct sshkey_cert {
   struct sshbuf *certblob ;
   u_int___0 type ;
   u_int64_t serial ;
   char *key_id ;
   u_int___0 nprincipals ;
   char **principals ;
   u_int64_t valid_after ;
   u_int64_t valid_before ;
   struct sshbuf *critical ;
   struct sshbuf *extensions ;
   struct sshkey *signature_key ;
};
#line 640 "../openssh.h"
struct sshkey {
   int type ;
   int flags ;
   RSA *rsa ;
   DSA *dsa ;
   int ecdsa_nid ;
   void *ecdsa ;
   u_char___0 *ed25519_sk ;
   u_char___0 *ed25519_pk ;
   struct sshkey_cert *cert ;
};
#line 652
struct ssh;
#line 652 "../openssh.h"
struct kex {
   u_char___0 *session_id ;
   size_t session_id_len ;
   struct newkeys *newkeys[2] ;
   u_int___0 we_need ;
   u_int___0 dh_need ;
   int server ;
   char *name ;
   char *hostkey_alg ;
   int hostkey_type ;
   int hostkey_nid ;
   u_int___0 kex_type ;
   int rsa_sha2 ;
   int ext_info_c ;
   struct sshbuf *my ;
   struct sshbuf *peer ;
   sig_atomic_t done ;
   u_int___0 flags ;
   int hash_alg ;
   int ec_nid ;
   char *client_version_string ;
   char *server_version_string ;
   char *failed_choice ;
   int (*verify_host_key)(struct sshkey * , struct ssh * ) ;
   struct sshkey *(*load_host_public_key)(int  , int  , struct ssh * ) ;
   struct sshkey *(*load_host_private_key)(int  , int  , struct ssh * ) ;
   int (*host_key_index)(struct sshkey * , int  , struct ssh * ) ;
   int (*sign)(struct sshkey * , struct sshkey * , u_char___0 ** , size_t * , u_char___0 const   * ,
               size_t  , char const   * , u_int___0  ) ;
   int (*kex[9])(struct ssh * ) ;
   void *dh ;
   u_int___0 min ;
   u_int___0 max ;
   u_int___0 nbits ;
   void *ec_client_key ;
   void const   *ec_group ;
   u_char___0 c25519_client_key[32] ;
   u_char___0 c25519_client_pubkey[32] ;
};
#line 751 "../openssh.h"
struct Forward {
   char *listen_host ;
   int listen_port ;
   char *listen_path ;
   char *connect_host ;
   int connect_port ;
   char *connect_path ;
   int allocated_port ;
   int handle ;
};
#line 762 "../openssh.h"
struct ForwardOptions {
   int gateway_ports ;
   mode_t streamlocal_bind_mask ;
   int streamlocal_bind_unlink ;
};
#line 793
enum __anonenum_LogLevel_27 {
    SYSLOG_LEVEL_QUIET = 0,
    SYSLOG_LEVEL_FATAL = 1,
    SYSLOG_LEVEL_ERROR = 2,
    SYSLOG_LEVEL_INFO = 3,
    SYSLOG_LEVEL_VERBOSE = 4,
    SYSLOG_LEVEL_DEBUG1 = 5,
    SYSLOG_LEVEL_DEBUG2 = 6,
    SYSLOG_LEVEL_DEBUG3 = 7,
    SYSLOG_LEVEL_NOT_SET = -1
} ;
#line 793 "../openssh.h"
typedef enum __anonenum_LogLevel_27 LogLevel;
#line 807 "../openssh.h"
struct allowed_cname {
   char *source_list ;
   char *target_list ;
};
#line 812 "../openssh.h"
struct __anonstruct_Options_28 {
   int forward_agent ;
   int forward_x11 ;
   int forward_x11_timeout ;
   int forward_x11_trusted ;
   int exit_on_forward_failure ;
   char *xauth_location ;
   struct ForwardOptions fwd_opts ;
   int use_privileged_port ;
   int rhosts_rsa_authentication ;
   int rsa_authentication ;
   int pubkey_authentication ;
   int hostbased_authentication ;
   int challenge_response_authentication ;
   int gss_authentication ;
   int gss_deleg_creds ;
   int password_authentication ;
   int kbd_interactive_authentication ;
   char *kbd_interactive_devices ;
   int batch_mode ;
   int check_host_ip ;
   int strict_host_key_checking ;
   int compression ;
   int compression_level ;
   int tcp_keep_alive ;
   int ip_qos_interactive ;
   int ip_qos_bulk ;
   LogLevel log_level ;
   int port ;
   int address_family ;
   int connection_attempts ;
   int connection_timeout ;
   int number_of_password_prompts ;
   int cipher ;
   char *ciphers ;
   char *macs ;
   char *hostkeyalgorithms ;
   char *kex_algorithms ;
   int protocol ;
   char *hostname ;
   char *host_key_alias ;
   char *proxy_command ;
   char *user ;
   int escape_char ;
   u_int___0 num_system_hostfiles ;
   char *system_hostfiles[32] ;
   u_int___0 num_user_hostfiles ;
   char *user_hostfiles[32] ;
   char *preferred_authentications ;
   char *bind_address ;
   char *pkcs11_provider ;
   int verify_host_key_dns ;
   int num_identity_files ;
   char *identity_files[100] ;
   int identity_file_userprovided[100] ;
   struct sshkey *identity_keys[100] ;
   int num_local_forwards ;
   struct Forward *local_forwards ;
   int num_remote_forwards ;
   struct Forward *remote_forwards ;
   int clear_forwardings ;
   int enable_ssh_keysign ;
   int64_t rekey_limit ;
   int rekey_interval ;
   int no_host_authentication_for_localhost ;
   int identities_only ;
   int server_alive_interval ;
   int server_alive_count_max ;
   int num_send_env ;
   char *send_env[256] ;
   char *control_path ;
   int control_master ;
   int control_persist ;
   int control_persist_timeout ;
   int hash_known_hosts ;
   int tun_open ;
   int tun_local ;
   int tun_remote ;
   char *local_command ;
   int permit_local_command ;
   int visual_host_key ;
   int use_roaming ;
   int request_tty ;
   int proxy_use_fdpass ;
   int num_canonical_domains ;
   char *canonical_domains[32] ;
   int canonicalize_hostname ;
   int canonicalize_max_dots ;
   int canonicalize_fallback_local ;
   int num_permitted_cnames ;
   struct allowed_cname permitted_cnames[32] ;
   char *revoked_host_keys ;
   int fingerprint_hash ;
   int update_hostkeys ;
   char *hostbased_key_types ;
   char *ignored_unknown ;
};
#line 812 "../openssh.h"
typedef struct __anonstruct_Options_28 Options;
#line 1019
struct session_state;
#line 1019
struct key_entry;
#line 1019 "../openssh.h"
struct __anonstruct_private_keys_31 {
   struct key_entry *tqh_first ;
   struct key_entry **tqh_last ;
};
#line 1019 "../openssh.h"
struct __anonstruct_public_keys_32 {
   struct key_entry *tqh_first ;
   struct key_entry **tqh_last ;
};
#line 1019 "../openssh.h"
struct ssh {
   struct session_state *state ;
   struct kex *kex ;
   char *remote_ipaddr ;
   int remote_port ;
   char *local_ipaddr ;
   int local_port ;
   char *log_preamble ;
   int dispatch_skip_packets ;
   int compat ;
   struct __anonstruct_private_keys_31 private_keys ;
   struct __anonstruct_public_keys_32 public_keys ;
   void *app_data ;
};
#line 1054 "../openssh.h"
struct packet_state {
   u_int32_t___0 seqnr ;
   u_int32_t___0 packets ;
   u_int64_t blocks ;
   u_int64_t bytes ;
};
#line 1061 "../openssh.h"
struct __anonstruct_next_33 {
   struct packet *tqe_next ;
   struct packet **tqe_prev ;
};
#line 1061 "../openssh.h"
struct packet {
   struct __anonstruct_next_33 next ;
   u_char___0 type ;
   struct sshbuf *payload ;
};
#line 1067 "../openssh.h"
typedef int ssh_packet_hook_fn(struct ssh * , struct sshbuf * , u_char___0 * , void * );
#line 1070 "../openssh.h"
typedef int z_stream;
#line 1073
struct sshcipher_ctx;
#line 1073
struct sshmac;
#line 1073 "../openssh.h"
struct __anonstruct_outgoing_34 {
   struct packet *tqh_first ;
   struct packet **tqh_last ;
};
#line 1073 "../openssh.h"
struct session_state {
   int connection_in ;
   int connection_out ;
   u_int___0 remote_protocol_flags ;
   struct sshcipher_ctx *receive_context ;
   struct sshcipher_ctx *send_context ;
   struct sshbuf *input ;
   struct sshbuf *output ;
   struct sshbuf *outgoing_packet ;
   struct sshbuf *incoming_packet ;
   struct sshbuf *compression_buffer ;
   z_stream compression_in_stream ;
   z_stream compression_out_stream ;
   int compression_in_started ;
   int compression_out_started ;
   int compression_in_failures ;
   int compression_out_failures ;
   int packet_compression ;
   u_int___0 max_packet_size ;
   int initialized ;
   int interactive_mode ;
   int server_side ;
   int after_authentication ;
   int keep_alive_timeouts ;
   int packet_timeout_ms ;
   struct newkeys *newkeys[2] ;
   struct packet_state p_read ;
   struct packet_state p_send ;
   u_int64_t max_blocks_in ;
   u_int64_t max_blocks_out ;
   u_int64_t rekey_limit ;
   u_int32_t___0 rekey_interval ;
   time_t rekey_time ;
   u_char___0 ssh1_key[32] ;
   u_int___0 ssh1_keylen ;
   u_char___0 extra_pad ;
   u_int___0 packet_discard ;
   size_t packet_discard_mac_already ;
   struct sshmac *packet_discard_mac ;
   u_int___0 packlen ;
   int rekeying ;
   int mux ;
   int set_interactive_called ;
   int set_maxsize_called ;
   int cipher_warning_done ;
   char *deattack ;
   ssh_packet_hook_fn *hook_in ;
   void *hook_in_ctx ;
   struct __anonstruct_outgoing_34 outgoing ;
};
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 12 "openssh_leak_1.c"
Options options  ;
#line 13 "openssh_leak_1.c"
struct ssh *active_state  ;
#line 15 "openssh_leak_1.c"
char *strsep(char **stringp , char const   *delim ) 
{ 
  char *s ;
  char const   *spanp ;
  int c ;
  int sc ;
  char *tok ;
  char *tmp ;
  char const   *tmp___0 ;

  {
#line 23
  s = *stringp;
#line 23
  if ((unsigned long )s == (unsigned long )((void *)0)) {
#line 24
    return ((char *)((void *)0));
  }
#line 25
  tok = s;
#line 25
  while (1) {
#line 26
    tmp = s;
#line 26
    s ++;
#line 26
    c = (int )*tmp;
#line 27
    spanp = delim;
#line 28
    while (1) {
#line 29
      tmp___0 = spanp;
#line 29
      spanp ++;
#line 29
      sc = (int )*tmp___0;
#line 29
      if (sc == c) {
#line 30
        if (c == 0) {
#line 31
          s = (char *)((void *)0);
        } else {
#line 33
          *(s + -1) = (char)0;
        }
#line 34
        *stringp = s;
#line 35
        return (tok);
      }
#line 28
      if (! (sc != 0)) {
#line 28
        break;
      }
    }
  }
}
}
#line 57
extern int ( /* missing proto */  strlen)() ;
#line 42 "openssh_leak_1.c"
size_t strlcat(char *dst , char const   *src , size_t siz ) 
{ 
  char *d ;
  char const   *s ;
  size_t n ;
  size_t dlen ;
  size_t tmp ;
  int tmp___0 ;
  char *tmp___1 ;

  {
#line 45
  d = dst;
#line 46
  s = src;
#line 47
  n = siz;
#line 51
  while (1) {
#line 51
    tmp = n;
#line 51
    n --;
#line 51
    if (tmp != 0UL) {
#line 51
      if (! ((int )*d != 0)) {
#line 51
        break;
      }
    } else {
#line 51
      break;
    }
#line 52
    d ++;
  }
#line 53
  dlen = (size_t )(d - dst);
#line 54
  n = siz - dlen;
#line 56
  if (n == 0UL) {
#line 57
    tmp___0 = strlen(s);
#line 57
    return (dlen + (size_t )tmp___0);
  }
#line 58
  while ((int const   )*s != 0) {
#line 59
    if (n != 1UL) {
#line 60
      tmp___1 = d;
#line 60
      d ++;
#line 60
      *tmp___1 = (char )*s;
#line 61
      n --;
    }
#line 63
    s ++;
  }
#line 65
  *d = (char )'\000';
#line 67
  return (dlen + (size_t )(s - src));
}
}
#line 75 "openssh_leak_1.c"
int match_pattern(char const   *s , char const   *pattern ) 
{ 


  {
#line 78
  while (1) {
#line 80
    if (! *pattern) {
#line 81
      return (! *s);
    }
#line 83
    if ((int const   )*pattern == 42) {
#line 85
      pattern ++;
#line 88
      if (! *pattern) {
#line 89
        return (1);
      }
#line 92
      if ((int const   )*pattern != 63) {
#line 92
        if ((int const   )*pattern != 42) {
#line 98
          while (*s) {
#line 99
            if ((int const   )*s == (int const   )*pattern) {
#line 100
              return (1);
            }
#line 98
            s ++;
          }
#line 102
          return (0);
        }
      }
#line 108
      while (*s) {
#line 109
        return (1);
#line 108
        s ++;
      }
#line 111
      return (0);
    }
#line 117
    if (! *s) {
#line 118
      return (0);
    }
#line 121
    if ((int const   )*pattern != 63) {
#line 121
      if ((int const   )*pattern != (int const   )*s) {
#line 122
        return (0);
      }
    }
#line 125
    s ++;
#line 126
    pattern ++;
  }
}
}
#line 154
extern int ( /* missing proto */  isupper)() ;
#line 154
extern int ( /* missing proto */  tolower)() ;
#line 130 "openssh_leak_1.c"
int match_pattern_list(char const   *string , char const   *pattern , int dolower ) 
{ 
  char sub[1024] ;
  int negated ;
  int got_positive ;
  unsigned int i ;
  unsigned int subi ;
  unsigned int len ;
  int tmp ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;

  {
#line 136
  tmp = strlen(pattern);
#line 136
  len = (unsigned int )tmp;
#line 138
  got_positive = 0;
#line 139
  i = 0U;
#line 139
  while (i < len) {
#line 141
    if ((int const   )*(pattern + i) == 33) {
#line 142
      negated = 1;
#line 143
      i ++;
    } else {
#line 145
      negated = 0;
    }
#line 151
    subi = 0U;
#line 151
    while (1) {
#line 151
      if (i < len) {
#line 151
        if ((unsigned long )subi < sizeof(sub) - 1UL) {
#line 151
          if (! ((int const   )*(pattern + i) != 44)) {
#line 151
            break;
          }
        } else {
#line 151
          break;
        }
      } else {
#line 151
        break;
      }
#line 154
      if (dolower) {
#line 154
        tmp___2 = isupper((int )((u_char___0 )*(pattern + i)));
#line 154
        if (tmp___2) {
#line 154
          tmp___1 = tolower((int )((u_char___0 )*(pattern + i)));
#line 154
          sub[subi] = (char )tmp___1;
        } else {
#line 154
          sub[subi] = (char )*(pattern + i);
        }
      } else {
#line 154
        sub[subi] = (char )*(pattern + i);
      }
#line 151
      subi ++;
#line 151
      i ++;
    }
#line 157
    if ((unsigned long )subi >= sizeof(sub) - 1UL) {
#line 158
      return (0);
    }
#line 161
    if (i < len) {
#line 161
      if ((int const   )*(pattern + i) == 44) {
#line 162
        i ++;
      }
    }
#line 165
    sub[subi] = (char )'\000';
#line 168
    tmp___3 = match_pattern(string, (char const   *)(sub));
#line 168
    if (tmp___3) {
#line 169
      if (negated) {
#line 170
        return (-1);
      } else {
#line 172
        got_positive = 1;
      }
    }
  }
#line 180
  return (got_positive);
}
}
#line 188
extern int ( /* missing proto */  strdup)() ;
#line 183 "openssh_leak_1.c"
char *match_filter_list(char const   *proposal , char const   *filter ) 
{ 
  size_t len ;
  int tmp ;
  char *fix_prop ;
  void *tmp___0 ;
  char *orig_prop ;
  int tmp___1 ;
  char *cp ;
  char *tmp___2 ;
  int tmp___3 ;

  {
#line 186
  tmp = strlen(proposal);
#line 186
  len = (size_t )(tmp + 1);
#line 187
  tmp___0 = malloc(len);
#line 187
  fix_prop = (char *)tmp___0;
#line 188
  tmp___1 = strdup(proposal);
#line 188
  orig_prop = (char *)tmp___1;
#line 191
  if ((unsigned long )fix_prop == (unsigned long )((void *)0)) {
#line 192
    free((void *)orig_prop);
#line 194
    return ((char *)((void *)0));
  } else
#line 191
  if ((unsigned long )orig_prop == (unsigned long )((void *)0)) {
#line 192
    free((void *)orig_prop);
#line 194
    return ((char *)((void *)0));
  }
#line 197
  tmp___2 = orig_prop;
#line 198
  *fix_prop = (char )'\000';
#line 199
  while (1) {
#line 199
    cp = strsep(& tmp___2, ",");
#line 199
    if (! ((unsigned long )cp != (unsigned long )((void *)0))) {
#line 199
      break;
    }
#line 200
    tmp___3 = match_pattern_list((char const   *)cp, filter, 0);
#line 200
    if (tmp___3 != 1) {
#line 201
      if ((int )*fix_prop != 0) {
#line 202
        strlcat(fix_prop, ",", len);
      }
#line 203
      strlcat(fix_prop, (char const   *)cp, len);
    }
  }
#line 206
  free((void *)orig_prop);
#line 207
  return (fix_prop);
}
}
#line 210 "openssh_leak_1.c"
int main(void) 
{ 
  char *proposal ;
  char *tmp ;

  {
#line 212
  tmp = match_filter_list("proposal", "filter");
#line 212
  proposal = tmp;
#line 213
  if ((unsigned long )proposal == (unsigned long )((void *)0)) {
#line 214
    printf((char const   * __restrict  )"match_filter_list failed\n");
  }
#line 215
  printf((char const   * __restrict  )"proposal : %s\n", proposal);
#line 216
  return (0);
}
}
