/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 124 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
#line 125 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
#line 126 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
#line 127 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
#line 129 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 130 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 150 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 203 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef unsigned long u_int64_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 46 "/usr/include/x86_64-linux-gnu/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   __syscall_slong_t __glibc_reserved[3] ;
};
#line 196 "../stdio.h"
typedef unsigned int u_int___0;
#line 200 "../stdio.h"
typedef int int32_t___0;
#line 207 "../stdio.h"
typedef unsigned char u_char___0;
#line 364 "../openssh.h"
typedef u_int___0 BN_ULONG;
#line 365 "../openssh.h"
struct __anonstruct_Buffer_25 {
   u_char___0 *buf ;
   u_int___0 alloc ;
   u_int___0 offset ;
   u_int___0 end ;
};
#line 365 "../openssh.h"
typedef struct __anonstruct_Buffer_25 Buffer;
#line 372 "../openssh.h"
struct bignum_st {
   BN_ULONG *d ;
   int top ;
   int dmax ;
   int neg ;
   int flags ;
};
#line 390 "../openssh.h"
typedef struct bignum_st BIGNUM;
#line 391 "../openssh.h"
struct rsa_st {
   int pad ;
   int32_t___0 version ;
   void const   *meth ;
   void *engine ;
   BIGNUM *n ;
   BIGNUM *e ;
   BIGNUM *d ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *dmp1 ;
   BIGNUM *dmq1 ;
   BIGNUM *iqmp ;
   void *pss ;
   int ex_data ;
   int references ;
   int flags ;
   void *_method_mod_n ;
   void *_method_mod_p ;
   void *_method_mod_q ;
   char *bignum_data ;
   void *blinding ;
   void *mt_blinding ;
   void *lock ;
};
#line 391 "../openssh.h"
typedef struct rsa_st RSA;
#line 434 "../openssh.h"
struct dsa_st {
   int pad ;
   int32_t___0 version ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *g ;
   BIGNUM *pub_key ;
   BIGNUM *priv_key ;
   int flags ;
};
#line 434 "../openssh.h"
typedef struct dsa_st DSA;
#line 1191
struct Key;
#line 1191 "../openssh.h"
typedef struct Key Key;
#line 1203 "../openssh.h"
struct KeyCert {
   Buffer certblob ;
   u_int___0 type ;
   u_int64_t serial ;
   char *key_id ;
   u_int___0 nprincipals ;
   char **principals ;
   u_int64_t valid_after ;
   u_int64_t valid_before ;
   Buffer critical ;
   Buffer extensions ;
   Key *signature_key ;
};
#line 1216 "../openssh.h"
struct Key {
   int type ;
   int flags ;
   RSA *rsa ;
   DSA *dsa ;
   int ecdsa_nid ;
   void *ecdsa ;
   struct KeyCert *cert ;
   u_char___0 *ed25519_sk ;
   u_char___0 *ed25519_pk ;
};
#line 196 "../stdio.h"
typedef unsigned int u_int___1;
#line 207 "../stdio.h"
typedef unsigned char u_char___1;
#line 213 "../stdio.h"
typedef int pid_t___1;
#line 245 "../stdio.h"
struct passwd___0 {
   char *pw_name ;
   char *pw_passwd ;
   int pw_uid ;
   int pw_gid ;
   int pw_change ;
   char *pw_class ;
   char *pw_gecos ;
   char *pw_dir ;
   char *pw_shell ;
   int pw_expire ;
};
#line 365 "../openssh.h"
struct __anonstruct_Buffer_37 {
   u_char___1 *buf ;
   u_int___1 alloc ;
   u_int___1 offset ;
   u_int___1 end ;
};
#line 365 "../openssh.h"
typedef struct __anonstruct_Buffer_37 Buffer___0;
#line 1191 "../openssh.h"
typedef struct Key Key___0;
#line 1284 "../openssh.h"
struct __anonstruct_AuthenticationConnection_48 {
   int fd ;
   Buffer___0 identities ;
   int howmany ;
};
#line 1284 "../openssh.h"
typedef struct __anonstruct_AuthenticationConnection_48 AuthenticationConnection___0;
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 170
extern struct _IO_FILE *stderr ;
#line 242
extern int fflush(FILE *__stream ) ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 386
extern  __attribute__((__nothrow__)) int ( /* format attribute */  snprintf)(char * __restrict  __s ,
                                                                             size_t __maxlen ,
                                                                             char const   * __restrict  __format 
                                                                             , ...) ;
#line 846
extern void perror(char const   *__s ) ;
#line 483 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 564
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1), __leaf__)) getenv)(char const   *__name ) ;
#line 50 "/usr/include/x86_64-linux-gnu/bits/errno.h"
extern  __attribute__((__nothrow__)) int *( __attribute__((__leaf__)) __errno_location)(void)  __attribute__((__const__)) ;
#line 208 "/usr/include/x86_64-linux-gnu/sys/stat.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) stat)(char const   * __restrict  __file ,
                                                                                             struct stat * __restrict  __buf ) ;
#line 158 "openssh_df_6.c"
char *__progname  ;
#line 168 "openssh_df_6.c"
static char *pass  =    (char *)((void *)0);
#line 173
extern int ( /* missing proto */  memset)() ;
#line 173
extern int ( /* missing proto */  strlen)() ;
#line 169 "openssh_df_6.c"
void clear_pass(void) 
{ 
  int tmp ;

  {
#line 172
  if (pass) {
#line 173
    tmp = strlen(pass);
#line 173
    memset(pass, 0, tmp);
#line 174
    free((void *)pass);
#line 175
    pass = (char *)((void *)0);
  }
#line 177
  return;
}
}
#line 189
extern int ( /* missing proto */  error)() ;
#line 189
extern int ( /* missing proto */  strerror)() ;
#line 192
extern int ( /* missing proto */  pipe)() ;
#line 194
extern int ( /* missing proto */  fork)() ;
#line 197
extern int ( /* missing proto */  close)() ;
#line 198
extern int ( /* missing proto */  dup2)() ;
#line 200
extern int ( /* missing proto */  execlp)() ;
#line 204
extern int ( /* missing proto */  read)() ;
#line 206
extern int ( /* missing proto */  waitpid)() ;
#line 210
extern int ( /* missing proto */  strdup)() ;
#line 211
extern int ( /* missing proto */  strchr)() ;
#line 179 "openssh_df_6.c"
char *ssh_askpass(char *askpass , char *msg ) 
{ 
  pid_t___1 pid ;
  size_t len ;
  char *nl ;
  char *pass___0 ;
  int p[2] ;
  int status ;
  char buf[1024] ;
  int *tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int *tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int *tmp___5 ;
  int tmp___6 ;
  int *tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int *tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;

  {
#line 188
  tmp___1 = fflush(stdout);
#line 188
  if (tmp___1 != 0) {
#line 189
    tmp = __errno_location();
#line 189
    tmp___0 = strerror(*tmp);
#line 189
    error("ssh_askpass: fflush: %s", tmp___0);
  }
#line 190
  if ((unsigned long )askpass == (unsigned long )((void *)0)) {
#line 191
    printf((char const   * __restrict  )"internal error: askpass undefined%s", "");
#line 191
    exit(1);
  }
#line 192
  tmp___4 = pipe(p);
#line 192
  if (tmp___4 < 0) {
#line 193
    tmp___2 = __errno_location();
#line 193
    tmp___3 = strerror(*tmp___2);
#line 193
    printf((char const   * __restrict  )"ssh_askpass: pipe: %s", tmp___3);
#line 193
    exit(1);
  }
#line 194
  pid = fork();
#line 194
  if (pid < 0) {
#line 195
    tmp___5 = __errno_location();
#line 195
    tmp___6 = strerror(*tmp___5);
#line 195
    printf((char const   * __restrict  )"ssh_askpass: fork: %s", tmp___6);
#line 195
    exit(1);
  }
#line 196
  if (pid == 0) {
#line 197
    close(p[0]);
#line 198
    tmp___9 = dup2(p[1], 1);
#line 198
    if (tmp___9 < 0) {
#line 199
      tmp___7 = __errno_location();
#line 199
      tmp___8 = strerror(*tmp___7);
#line 199
      printf((char const   * __restrict  )"ssh_askpass: dup2: %s", tmp___8);
#line 199
      exit(1);
    }
#line 200
    execlp(askpass, askpass, msg, (char *)0);
#line 201
    printf((char const   * __restrict  )"ssh_askpass: exec(%s)", askpass);
#line 201
    exit(1);
  }
#line 203
  close(p[1]);
#line 204
  tmp___10 = read(p[0], buf, sizeof(buf));
#line 204
  len = (size_t )tmp___10;
#line 205
  close(p[0]);
#line 206
  while (1) {
#line 206
    tmp___12 = waitpid(pid, & status, 0);
#line 206
    if (! (tmp___12 < 0)) {
#line 206
      break;
    }
#line 207
    tmp___11 = __errno_location();
#line 207
    if (*tmp___11 != 4) {
#line 208
      break;
    }
  }
#line 209
  if (len <= 1UL) {
#line 210
    tmp___13 = strdup("");
#line 210
    return ((char *)tmp___13);
  }
#line 211
  tmp___14 = strchr(buf, '\n');
#line 211
  nl = (char *)tmp___14;
#line 212
  if (nl) {
#line 213
    *nl = (char )'\000';
  }
#line 214
  tmp___15 = strdup(buf);
#line 214
  pass___0 = (char *)tmp___15;
#line 215
  memset(buf, 0, sizeof(buf));
#line 216
  return (pass___0);
}
}
#line 226
extern int ( /* missing proto */  isatty)() ;
#line 240
extern int ( /* missing proto */  key_load_private)() ;
#line 258
extern int ( /* missing proto */  read_passphrase)() ;
#line 262
extern int ( /* missing proto */  strcmp)() ;
#line 271
extern int ( /* missing proto */  strlcpy)() ;
#line 274
extern int ( /* missing proto */  ssh_add_identity)() ;
#line 279
extern int ( /* missing proto */  key_free)() ;
#line 219 "openssh_df_6.c"
void add_file(AuthenticationConnection___0 *ac , char const   *filename ) 
{ 
  struct stat st ;
  Key___0 *private ;
  char *comment ;
  char *askpass ;
  char buf[1024] ;
  char msg[1024] ;
  int interactive ;
  int tmp ;
  int tmp___0 ;
  char *tmp___1 ;
  char *tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;

  {
#line 224
  comment = (char *)((void *)0);
#line 224
  askpass = (char *)((void *)0);
#line 226
  tmp = isatty(0);
#line 226
  interactive = tmp;
#line 228
  tmp___0 = stat((char const   * __restrict  )filename, (struct stat * __restrict  )(& st));
#line 228
  if (tmp___0 < 0) {
#line 229
    perror(filename);
#line 230
    exit(1);
  }
#line 232
  if (! interactive) {
#line 232
    tmp___2 = getenv("DISPLAY");
#line 232
    if (tmp___2) {
#line 233
      tmp___1 = getenv("SSH_ASKPASS");
#line 233
      if (tmp___1) {
#line 234
        askpass = getenv("SSH_ASKPASS");
      } else {
#line 236
        askpass = (char *)"/usr/X11R6/bin/ssh-askpass";
      }
    }
  }
#line 240
  tmp___3 = key_load_private(filename, "", & comment);
#line 240
  private = (Key___0 *)tmp___3;
#line 241
  if ((unsigned long )comment == (unsigned long )((void *)0)) {
#line 242
    tmp___4 = strdup(filename);
#line 242
    comment = (char *)tmp___4;
  }
#line 244
  if ((unsigned long )private == (unsigned long )((void *)0)) {
#line 244
    if ((unsigned long )pass != (unsigned long )((void *)0)) {
#line 245
      tmp___5 = key_load_private(filename, pass, (void *)0);
#line 245
      private = (Key___0 *)tmp___5;
    }
  }
#line 246
  if ((unsigned long )private == (unsigned long )((void *)0)) {
#line 248
    clear_pass();
#line 249
    printf((char const   * __restrict  )"Need passphrase for %.200s\n", filename);
#line 250
    if (! interactive) {
#line 250
      if ((unsigned long )askpass == (unsigned long )((void *)0)) {
#line 251
        free((void *)comment);
#line 252
        return;
      }
    }
#line 254
    snprintf((char * __restrict  )(msg), sizeof(msg), (char const   * __restrict  )"Enter passphrase for %.200s",
             comment);
#line 255
    while (1) {
#line 256
      if (interactive) {
#line 257
        snprintf((char * __restrict  )(buf), sizeof(buf), (char const   * __restrict  )"%s: ",
                 msg);
#line 258
        tmp___6 = read_passphrase(buf, 1);
#line 258
        pass = (char *)tmp___6;
      } else {
#line 260
        pass = ssh_askpass(askpass, msg);
      }
#line 262
      tmp___7 = strcmp(pass, "");
#line 262
      if (tmp___7 == 0) {
#line 263
        free((void *)pass);
#line 264
        free((void *)comment);
#line 265
        return;
      }
#line 267
      tmp___8 = key_load_private(filename, pass, & comment);
#line 267
      private = (Key___0 *)tmp___8;
#line 268
      if ((unsigned long )private != (unsigned long )((void *)0)) {
#line 269
        break;
      }
#line 270
      clear_pass();
#line 271
      strlcpy(msg, "Bad passphrase, try again", sizeof(msg));
    }
  }
#line 274
  tmp___9 = ssh_add_identity(ac, private, comment);
#line 274
  if (tmp___9) {
#line 275
    fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"Identity added: %s (%s)\n",
            filename, comment);
  } else {
#line 277
    fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"Could not add identity: %s\n",
            filename);
  }
#line 278
  free((void *)comment);
#line 279
  key_free(private);
#line 280
  return;
}
}
#line 292
extern int ( /* missing proto */  get_progname)() ;
#line 293
extern int ( /* missing proto */  init_rng)() ;
#line 295
extern int ( /* missing proto */  SSLeay_add_all_algorithms)() ;
#line 298
extern int ( /* missing proto */  ssh_get_authentication_connection)() ;
#line 306
extern int ( /* missing proto */  list_identities)() ;
#line 316
extern int ( /* missing proto */  delete_all)() ;
#line 322
extern int ( /* missing proto */  delete_file)() ;
#line 327
extern int ( /* missing proto */  getpwuid)() ;
#line 327
extern int ( /* missing proto */  getuid)() ;
#line 331
extern int ( /* missing proto */  ssh_close_authentication_connection)() ;
#line 282 "openssh_df_6.c"
int main(int argc , char **argv ) 
{ 
  AuthenticationConnection___0 *ac ;
  struct passwd___0 *pw ;
  char buf[1024] ;
  int no_files ;
  int i ;
  int deleting ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;

  {
#line 285
  ac = (AuthenticationConnection___0 *)((void *)0);
#line 288
  no_files = 1;
#line 290
  deleting = 0;
#line 292
  tmp = get_progname(*(argv + 0));
#line 292
  __progname = (char *)tmp;
#line 293
  init_rng();
#line 295
  SSLeay_add_all_algorithms();
#line 298
  tmp___0 = ssh_get_authentication_connection();
#line 298
  ac = (AuthenticationConnection___0 *)tmp___0;
#line 299
  if ((unsigned long )ac == (unsigned long )((void *)0)) {
#line 300
    fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"Could not open a connection to your authentication agent.\n");
#line 301
    exit(1);
  }
#line 303
  i = 1;
#line 303
  while (i < argc) {
#line 304
    tmp___2 = strcmp(*(argv + i), "-l");
#line 304
    if (tmp___2 == 0) {
#line 304
      goto _L;
    } else {
#line 304
      tmp___3 = strcmp(*(argv + i), "-L");
#line 304
      if (tmp___3 == 0) {
        _L: /* CIL Label */ 
#line 306
        if ((int )*(*(argv + i) + 1) == 108) {
#line 306
          tmp___1 = 1;
        } else {
#line 306
          tmp___1 = 0;
        }
#line 306
        list_identities(ac, tmp___1);
#line 308
        no_files = 0;
#line 309
        goto __Cont;
      }
    }
#line 311
    tmp___4 = strcmp(*(argv + i), "-d");
#line 311
    if (tmp___4 == 0) {
#line 312
      deleting = 1;
#line 313
      goto __Cont;
    }
#line 315
    tmp___5 = strcmp(*(argv + i), "-D");
#line 315
    if (tmp___5 == 0) {
#line 316
      delete_all(ac);
#line 317
      no_files = 0;
#line 318
      goto __Cont;
    }
#line 320
    no_files = 0;
#line 321
    if (deleting) {
#line 322
      delete_file(ac, *(argv + i));
    } else {
#line 324
      add_file(ac, (char const   *)*(argv + i));
    }
    __Cont: /* CIL Label */ 
#line 303
    i ++;
  }
#line 326
  if (no_files) {
#line 327
    tmp___6 = getuid();
#line 327
    tmp___7 = getpwuid(tmp___6);
#line 327
    pw = (struct passwd___0 *)tmp___7;
#line 328
    if (! pw) {
#line 329
      tmp___8 = getuid();
#line 329
      fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"No user found with uid %u\n",
              (u_int___1 )tmp___8);
#line 331
      ssh_close_authentication_connection(ac);
#line 332
      exit(1);
    }
#line 334
    if (deleting) {
#line 335
      delete_file(ac, buf);
    } else {
#line 337
      add_file(ac, (char const   *)(buf));
    }
  }
#line 339
  clear_pass();
#line 340
  ssh_close_authentication_connection(ac);
#line 341
  return (0);
}
}
