/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 480
extern  __attribute__((__nothrow__)) void *( __attribute__((__warn_unused_result__,
__leaf__)) realloc)(void *__ptr , size_t __size ) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 564
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1), __leaf__)) getenv)(char const   *__name ) ;
#line 584
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(2), __leaf__)) setenv)(char const   *__name ,
                                                                                             char const   *__value ,
                                                                                             int __replace ) ;
#line 588
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) unsetenv)(char const   *__name ) ;
#line 50 "/usr/include/x86_64-linux-gnu/bits/errno.h"
extern  __attribute__((__nothrow__)) int *( __attribute__((__leaf__)) __errno_location)(void)  __attribute__((__const__)) ;
#line 169 "../git.h"
extern int ( /* missing proto */  memmove)() ;
#line 174
extern int ( /* missing proto */  strdup)() ;
#line 410 "../git.h"
void *xrealloc(void *ptr , size_t size ) 
{ 
  void *ret ;

  {
#line 414
  ret = realloc(ptr, size);
#line 415
  if (! ret) {
#line 415
    if (! size) {
#line 416
      ret = realloc(ptr, (size_t )1);
    }
  }
#line 417
  if (! ret) {
#line 418
    ret = realloc(ptr, size);
#line 419
    if (! ret) {
#line 419
      if (! size) {
#line 420
        ret = realloc(ptr, (size_t )1);
      }
    }
#line 421
    if (! ret) {
#line 422
      printf((char const   * __restrict  )"Out of memory, realloc failed%s", "");
#line 422
      exit(1);
    }
  }
#line 424
  return (ret);
}
}
#line 55 "git_uaf_3.c"
char const   git_usage_string[304]  = 
#line 55 "git_uaf_3.c"
  {      (char const   )'g',      (char const   )'i',      (char const   )'t',      (char const   )' ', 
        (char const   )'[',      (char const   )'-',      (char const   )'-',      (char const   )'v', 
        (char const   )'e',      (char const   )'r',      (char const   )'s',      (char const   )'i', 
        (char const   )'o',      (char const   )'n',      (char const   )']',      (char const   )' ', 
        (char const   )'[',      (char const   )'-',      (char const   )'-',      (char const   )'h', 
        (char const   )'e',      (char const   )'l',      (char const   )'p',      (char const   )']', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'C', 
        (char const   )' ',      (char const   )'<',      (char const   )'p',      (char const   )'a', 
        (char const   )'t',      (char const   )'h',      (char const   )'>',      (char const   )']', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'c', 
        (char const   )' ',      (char const   )'n',      (char const   )'a',      (char const   )'m', 
        (char const   )'e',      (char const   )'=',      (char const   )'v',      (char const   )'a', 
        (char const   )'l',      (char const   )'u',      (char const   )'e',      (char const   )']', 
        (char const   )'\n',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )'[',      (char const   )'-',      (char const   )'-',      (char const   )'e', 
        (char const   )'x',      (char const   )'e',      (char const   )'c',      (char const   )'-', 
        (char const   )'p',      (char const   )'a',      (char const   )'t',      (char const   )'h', 
        (char const   )'[',      (char const   )'=',      (char const   )'<',      (char const   )'p', 
        (char const   )'a',      (char const   )'t',      (char const   )'h',      (char const   )'>', 
        (char const   )']',      (char const   )']',      (char const   )' ',      (char const   )'[', 
        (char const   )'-',      (char const   )'-',      (char const   )'h',      (char const   )'t', 
        (char const   )'m',      (char const   )'l',      (char const   )'-',      (char const   )'p', 
        (char const   )'a',      (char const   )'t',      (char const   )'h',      (char const   )']', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'-', 
        (char const   )'m',      (char const   )'a',      (char const   )'n',      (char const   )'-', 
        (char const   )'p',      (char const   )'a',      (char const   )'t',      (char const   )'h', 
        (char const   )']',      (char const   )' ',      (char const   )'[',      (char const   )'-', 
        (char const   )'-',      (char const   )'i',      (char const   )'n',      (char const   )'f', 
        (char const   )'o',      (char const   )'-',      (char const   )'p',      (char const   )'a', 
        (char const   )'t',      (char const   )'h',      (char const   )']',      (char const   )'\n', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )'[', 
        (char const   )'-',      (char const   )'p',      (char const   )' ',      (char const   )'|', 
        (char const   )' ',      (char const   )'-',      (char const   )'-',      (char const   )'p', 
        (char const   )'a',      (char const   )'g',      (char const   )'i',      (char const   )'n', 
        (char const   )'a',      (char const   )'t',      (char const   )'e',      (char const   )' ', 
        (char const   )'|',      (char const   )' ',      (char const   )'-',      (char const   )'-', 
        (char const   )'n',      (char const   )'o',      (char const   )'-',      (char const   )'p', 
        (char const   )'a',      (char const   )'g',      (char const   )'e',      (char const   )'r', 
        (char const   )']',      (char const   )' ',      (char const   )'[',      (char const   )'-', 
        (char const   )'-',      (char const   )'n',      (char const   )'o',      (char const   )'-', 
        (char const   )'r',      (char const   )'e',      (char const   )'p',      (char const   )'l', 
        (char const   )'a',      (char const   )'c',      (char const   )'e',      (char const   )'-', 
        (char const   )'o',      (char const   )'b',      (char const   )'j',      (char const   )'e', 
        (char const   )'c',      (char const   )'t',      (char const   )'s',      (char const   )']', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'-', 
        (char const   )'b',      (char const   )'a',      (char const   )'r',      (char const   )'e', 
        (char const   )']',      (char const   )'\n',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'-', 
        (char const   )'g',      (char const   )'i',      (char const   )'t',      (char const   )'-', 
        (char const   )'d',      (char const   )'i',      (char const   )'r',      (char const   )'=', 
        (char const   )'<',      (char const   )'p',      (char const   )'a',      (char const   )'t', 
        (char const   )'h',      (char const   )'>',      (char const   )']',      (char const   )' ', 
        (char const   )'[',      (char const   )'-',      (char const   )'-',      (char const   )'w', 
        (char const   )'o',      (char const   )'r',      (char const   )'k',      (char const   )'-', 
        (char const   )'t',      (char const   )'r',      (char const   )'e',      (char const   )'e', 
        (char const   )'=',      (char const   )'<',      (char const   )'p',      (char const   )'a', 
        (char const   )'t',      (char const   )'h',      (char const   )'>',      (char const   )']', 
        (char const   )' ',      (char const   )'[',      (char const   )'-',      (char const   )'-', 
        (char const   )'n',      (char const   )'a',      (char const   )'m',      (char const   )'e', 
        (char const   )'s',      (char const   )'p',      (char const   )'a',      (char const   )'c', 
        (char const   )'e',      (char const   )'=',      (char const   )'<',      (char const   )'n', 
        (char const   )'a',      (char const   )'m',      (char const   )'e',      (char const   )'>', 
        (char const   )']',      (char const   )'\n',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )' ',      (char const   )' ',      (char const   )' ', 
        (char const   )' ',      (char const   )'<',      (char const   )'c',      (char const   )'o', 
        (char const   )'m',      (char const   )'m',      (char const   )'a',      (char const   )'n', 
        (char const   )'d',      (char const   )'>',      (char const   )' ',      (char const   )'[', 
        (char const   )'<',      (char const   )'a',      (char const   )'r',      (char const   )'g', 
        (char const   )'s',      (char const   )'>',      (char const   )']',      (char const   )'\000'};
#line 62 "git_uaf_3.c"
char const   git_more_info_string[181]  = 
#line 62
  {      (char const   )'\'',      (char const   )'g',      (char const   )'i',      (char const   )'t', 
        (char const   )' ',      (char const   )'h',      (char const   )'e',      (char const   )'l', 
        (char const   )'p',      (char const   )' ',      (char const   )'-',      (char const   )'a', 
        (char const   )'\'',      (char const   )' ',      (char const   )'a',      (char const   )'n', 
        (char const   )'d',      (char const   )' ',      (char const   )'\'',      (char const   )'g', 
        (char const   )'i',      (char const   )'t',      (char const   )' ',      (char const   )'h', 
        (char const   )'e',      (char const   )'l',      (char const   )'p',      (char const   )' ', 
        (char const   )'-',      (char const   )'g',      (char const   )'\'',      (char const   )' ', 
        (char const   )'l',      (char const   )'i',      (char const   )'s',      (char const   )'t', 
        (char const   )' ',      (char const   )'a',      (char const   )'v',      (char const   )'a', 
        (char const   )'i',      (char const   )'l',      (char const   )'a',      (char const   )'b', 
        (char const   )'l',      (char const   )'e',      (char const   )' ',      (char const   )'s', 
        (char const   )'u',      (char const   )'b',      (char const   )'c',      (char const   )'o', 
        (char const   )'m',      (char const   )'m',      (char const   )'a',      (char const   )'n', 
        (char const   )'d',      (char const   )'s',      (char const   )' ',      (char const   )'a', 
        (char const   )'n',      (char const   )'d',      (char const   )' ',      (char const   )'s', 
        (char const   )'o',      (char const   )'m',      (char const   )'e',      (char const   )'\n', 
        (char const   )'c',      (char const   )'o',      (char const   )'n',      (char const   )'c', 
        (char const   )'e',      (char const   )'p',      (char const   )'t',      (char const   )' ', 
        (char const   )'g',      (char const   )'u',      (char const   )'i',      (char const   )'d', 
        (char const   )'e',      (char const   )'s',      (char const   )'.',      (char const   )' ', 
        (char const   )'S',      (char const   )'e',      (char const   )'e',      (char const   )' ', 
        (char const   )'\'',      (char const   )'g',      (char const   )'i',      (char const   )'t', 
        (char const   )' ',      (char const   )'h',      (char const   )'e',      (char const   )'l', 
        (char const   )'p',      (char const   )' ',      (char const   )'<',      (char const   )'c', 
        (char const   )'o',      (char const   )'m',      (char const   )'m',      (char const   )'a', 
        (char const   )'n',      (char const   )'d',      (char const   )'>',      (char const   )'\'', 
        (char const   )' ',      (char const   )'o',      (char const   )'r',      (char const   )' ', 
        (char const   )'\'',      (char const   )'g',      (char const   )'i',      (char const   )'t', 
        (char const   )' ',      (char const   )'h',      (char const   )'e',      (char const   )'l', 
        (char const   )'p',      (char const   )' ',      (char const   )'<',      (char const   )'c', 
        (char const   )'o',      (char const   )'n',      (char const   )'c',      (char const   )'e', 
        (char const   )'p',      (char const   )'t',      (char const   )'>',      (char const   )'\'', 
        (char const   )'\n',      (char const   )'t',      (char const   )'o',      (char const   )' ', 
        (char const   )'r',      (char const   )'e',      (char const   )'a',      (char const   )'d', 
        (char const   )' ',      (char const   )'a',      (char const   )'b',      (char const   )'o', 
        (char const   )'u',      (char const   )'t',      (char const   )' ',      (char const   )'a', 
        (char const   )' ',      (char const   )'s',      (char const   )'p',      (char const   )'e', 
        (char const   )'c',      (char const   )'i',      (char const   )'f',      (char const   )'i', 
        (char const   )'c',      (char const   )' ',      (char const   )'s',      (char const   )'u', 
        (char const   )'b',      (char const   )'c',      (char const   )'o',      (char const   )'m', 
        (char const   )'m',      (char const   )'a',      (char const   )'n',      (char const   )'d', 
        (char const   )' ',      (char const   )'o',      (char const   )'r',      (char const   )' ', 
        (char const   )'c',      (char const   )'o',      (char const   )'n',      (char const   )'c', 
        (char const   )'e',      (char const   )'p',      (char const   )'t',      (char const   )'.', 
        (char const   )'\000'};
#line 69 "git_uaf_3.c"
char *orig_cwd  ;
#line 70 "git_uaf_3.c"
static char const   *env_names[4]  = {      "GIT_DIR",      "GIT_WORK_TREE",      "GIT_IMPLICIT_WORK_TREE",      "GIT_PREFIX"};
#line 76 "git_uaf_3.c"
static char *orig_env[4]  ;
#line 77 "git_uaf_3.c"
static int saved_env_before_alias  ;
#line 83
extern int ( /* missing proto */  xgetcwd)() ;
#line 84
extern int ( /* missing proto */  ARRAY_SIZE)() ;
#line 79 "git_uaf_3.c"
static void save_env_before_alias(void) 
{ 
  int i ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 82
  saved_env_before_alias = 1;
#line 83
  tmp = xgetcwd();
#line 83
  orig_cwd = (char *)tmp;
#line 84
  i = 0;
#line 84
  while (1) {
#line 84
    tmp___1 = ARRAY_SIZE(env_names);
#line 84
    if (! (i < tmp___1)) {
#line 84
      break;
    }
#line 85
    orig_env[i] = getenv(env_names[i]);
#line 86
    if (orig_env[i]) {
#line 87
      tmp___0 = strdup(orig_env[i]);
#line 87
      orig_env[i] = (char *)tmp___0;
    }
#line 84
    i ++;
  }
#line 89
  return;
}
}
#line 94
extern int ( /* missing proto */  chdir)() ;
#line 98
extern int ( /* missing proto */  strcmp)() ;
#line 91 "git_uaf_3.c"
static void restore_env(int external_alias ) 
{ 
  int i ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 94
  if (! external_alias) {
#line 94
    if (orig_cwd) {
#line 94
      tmp = chdir(orig_cwd);
#line 94
      if (tmp) {
#line 95
        printf((char const   * __restrict  )"could not move to %s", orig_cwd);
#line 95
        exit(1);
      }
    }
  }
#line 96
  free((void *)orig_cwd);
#line 97
  i = 0;
#line 97
  while (1) {
#line 97
    tmp___1 = ARRAY_SIZE(env_names);
#line 97
    if (! (i < tmp___1)) {
#line 97
      break;
    }
#line 98
    if (external_alias) {
#line 98
      tmp___0 = strcmp(env_names[i], "GIT_PREFIX");
#line 98
      if (! tmp___0) {
#line 100
        goto __Cont;
      }
    }
#line 101
    if (orig_env[i]) {
#line 102
      setenv(env_names[i], (char const   *)orig_env[i], 1);
    } else {
#line 104
      unsetenv(env_names[i]);
    }
    __Cont: /* CIL Label */ 
#line 97
    i ++;
  }
#line 106
  return;
}
}
#line 121
extern int ( /* missing proto */  setup_git_directory_gently)() ;
#line 124
extern int ( /* missing proto */  alias_lookup)() ;
#line 130
extern int ( /* missing proto */  commit_pager_choice)() ;
#line 140
extern int ( /* missing proto */  run_command_v_opt)() ;
#line 147
extern int ( /* missing proto */  split_cmdline)() ;
#line 150
extern int ( /* missing proto */  handle_options)() ;
#line 165
extern int ( /* missing proto */  trace_argv_printf)() ;
#line 108 "git_uaf_3.c"
static int new_handle_alias(int *argcp , char const   ***argv ) 
{ 
  int envchanged ;
  int ret ;
  int saved_errno ;
  int *tmp ;
  int count ;
  int option_count ;
  char const   **new_argv ;
  char const   *alias_command ;
  char *alias_string ;
  int unused_nongit ;
  int unexpected ;
  int tmp___0 ;
  char const   **alias_argv ;
  int argc ;
  int i ;
  void *tmp___1 ;
  int tmp___2 ;
  int *tmp___3 ;

  {
#line 110
  envchanged = 0;
#line 110
  ret = 0;
#line 110
  tmp = __errno_location();
#line 110
  saved_errno = *tmp;
#line 118
  if (unexpected) {
#line 119
    goto err;
  }
#line 120
  save_env_before_alias();
#line 121
  setup_git_directory_gently(& unused_nongit);
#line 123
  alias_command = *(*argv + 0);
#line 124
  tmp___0 = alias_lookup(alias_command);
#line 124
  alias_string = (char *)tmp___0;
#line 125
  if (alias_string) {
#line 126
    if ((int )*(alias_string + 0) == 33) {
#line 128
      argc = *argcp;
#line 130
      commit_pager_choice();
#line 131
      restore_env(1);
#line 134
      tmp___1 = malloc(sizeof(*alias_argv) * (unsigned long )(argc + 1));
#line 134
      alias_argv = (char const   **)tmp___1;
#line 135
      *(alias_argv + 0) = (char const   *)(alias_string + 1);
#line 136
      i = 1;
#line 136
      while (i < argc) {
#line 137
        *(alias_argv + i) = *(*argv + i);
#line 136
        i ++;
      }
#line 138
      *(alias_argv + argc) = (char const   *)((void *)0);
#line 140
      ret = run_command_v_opt(alias_argv, 16);
#line 141
      if (ret >= 0) {
#line 142
        exit(ret);
      }
#line 144
      printf((char const   * __restrict  )"While expanding alias \'%s\':", alias_command);
#line 144
      exit(1);
    }
#line 147
    count = split_cmdline(alias_string, & new_argv);
#line 148
    if (count < 0) {
#line 149
      printf((char const   * __restrict  )"Bad alias.%s string: ", alias_command);
#line 149
      exit(1);
    }
#line 150
    option_count = handle_options(& new_argv, & count, & envchanged);
#line 151
    if (envchanged) {
#line 152
      printf((char const   * __restrict  )"alias \'%s\' changes environment variables\nYou can use \'!git\' in the alias to do this.",
             alias_command);
#line 152
      exit(1);
    }
#line 155
    memmove(new_argv - option_count, new_argv, (unsigned long )count * sizeof(char *));
#line 157
    new_argv -= option_count;
#line 159
    if (count < 1) {
#line 160
      printf((char const   * __restrict  )"empty alias for %s", alias_command);
#line 160
      exit(1);
    }
#line 162
    tmp___2 = strcmp(alias_command, *(new_argv + 0));
#line 162
    if (! tmp___2) {
#line 163
      printf((char const   * __restrict  )"recursive alias: %s", alias_command);
#line 163
      exit(1);
    }
#line 165
    trace_argv_printf(new_argv, "trace: alias expansion: %s =>", alias_command);
#line 169
    ret = 1;
  }
  err: 
#line 173
  restore_env(0);
#line 175
  tmp___3 = __errno_location();
#line 175
  *tmp___3 = saved_errno;
#line 177
  return (ret);
}
}
#line 180 "git_uaf_3.c"
static int handle_alias(int *argcp , char const   ***argv ) 
{ 
  int envchanged ;
  int ret ;
  int saved_errno ;
  int *tmp ;
  int count ;
  int option_count ;
  char const   **new_argv ;
  char const   *alias_command ;
  char *alias_string ;
  int unused_nongit ;
  int tmp___0 ;
  char const   **alias_argv ;
  int argc ;
  int i ;
  void *tmp___1 ;
  int tmp___2 ;
  int *tmp___3 ;

  {
#line 182
  envchanged = 0;
#line 182
  ret = 0;
#line 182
  tmp = __errno_location();
#line 182
  saved_errno = *tmp;
#line 189
  save_env_before_alias();
#line 190
  setup_git_directory_gently(& unused_nongit);
#line 192
  alias_command = *(*argv + 0);
#line 193
  tmp___0 = alias_lookup(alias_command);
#line 193
  alias_string = (char *)tmp___0;
#line 194
  if (alias_string) {
#line 195
    if ((int )*(alias_string + 0) == 33) {
#line 197
      argc = *argcp;
#line 199
      commit_pager_choice();
#line 200
      restore_env(1);
#line 203
      tmp___1 = malloc(sizeof(*alias_argv) * (unsigned long )(argc + 1));
#line 203
      alias_argv = (char const   **)tmp___1;
#line 204
      *(alias_argv + 0) = (char const   *)(alias_string + 1);
#line 205
      i = 1;
#line 205
      while (i < argc) {
#line 206
        *(alias_argv + i) = *(*argv + i);
#line 205
        i ++;
      }
#line 207
      *(alias_argv + argc) = (char const   *)((void *)0);
#line 209
      ret = run_command_v_opt(alias_argv, 16);
#line 210
      if (ret >= 0) {
#line 211
        exit(ret);
      }
#line 213
      printf((char const   * __restrict  )"While expanding alias \'%s\': ", alias_command);
#line 213
      exit(1);
    }
#line 216
    count = split_cmdline(alias_string, & new_argv);
#line 217
    if (count < 0) {
#line 218
      printf((char const   * __restrict  )"Bad alias.%s string: ", alias_command);
#line 218
      exit(1);
    }
#line 219
    option_count = handle_options(& new_argv, & count, & envchanged);
#line 220
    if (envchanged) {
#line 221
      printf((char const   * __restrict  )"alias \'%s\' changes environment variables\nYou can use \'!git\' in the alias to do this.",
             alias_command);
#line 221
      exit(1);
    }
#line 224
    memmove(new_argv - option_count, new_argv, (unsigned long )count * sizeof(char *));
#line 226
    new_argv -= option_count;
#line 228
    if (count < 1) {
#line 229
      printf((char const   * __restrict  )"empty alias for %s", alias_command);
#line 229
      exit(1);
    }
#line 231
    tmp___2 = strcmp(alias_command, *(new_argv + 0));
#line 231
    if (! tmp___2) {
#line 232
      printf((char const   * __restrict  )"recursive alias: %s", alias_command);
#line 232
      exit(1);
    }
#line 234
    trace_argv_printf(new_argv, "trace: alias expansion: %s =>", alias_command);
#line 238
    ret = 1;
  }
#line 241
  restore_env(0);
#line 243
  tmp___3 = __errno_location();
#line 243
  *tmp___3 = saved_errno;
#line 245
  return (ret);
}
}
#line 248 "git_uaf_3.c"
int main(int argc , char **argv ) 
{ 


  {
#line 250
  handle_alias(& argc, (char const   ***)(& argv));
#line 251
  new_handle_alias(& argc, (char const   ***)(& argv));
#line 252
  return (0);
}
}
