/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 29 "../include/common.h"
typedef int bool;
#line 34 "../include/common.h"
typedef void make_cleanup_ftype(void * );
#line 36 "../include/common.h"
struct cleanup {
   struct cleanup *next ;
   void (*function)(void * ) ;
   void (*free_arg)(void * ) ;
   void *arg ;
};
#line 388 "../include/vec.h"
struct vec_prefix {
   unsigned int num ;
   unsigned int alloc ;
   void *vec[1] ;
};
#line 9 "binutils_leak_6.c"
struct other_sections {
   char *name ;
   int secindex ;
};
#line 15 "binutils_leak_6.c"
struct section_addr_info {
   size_t num_sections ;
   struct other_sections other[1] ;
};
#line 21 "binutils_leak_6.c"
struct sect_opt {
   char const   *name ;
   char const   *value ;
};
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 480
extern  __attribute__((__nothrow__)) void *( __attribute__((__warn_unused_result__,
__leaf__)) realloc)(void *__ptr , size_t __size ) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 31 "../include/common.h"
bool true  =    1;
#line 32 "../include/common.h"
bool false  =    0;
#line 44 "../include/common.h"
static struct cleanup  const  sentinel_cleanup  =    {(struct cleanup *)0, (void (*)(void * ))0, (void (*)(void * ))0, (void *)0};
#line 49 "../include/common.h"
static struct cleanup *cleanup_chain  =    (struct cleanup *)(& sentinel_cleanup);
#line 50 "../include/common.h"
static struct cleanup *final_cleanup_chain  ;
#line 52
void discard_cleanups(struct cleanup *old_chain ) ;
#line 53
void discard_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) ;
#line 55
void discard_final_cleanups(struct cleanup *old_chain ) ;
#line 56
static void do_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) ;
#line 58
void do_cleanups(struct cleanup *old_chain ) ;
#line 59
static struct cleanup *make_my_cleanup2(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                        void *arg , void (*free_arg)(void * ) ) ;
#line 62
static struct cleanup *make_my_cleanup(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                       void *arg ) ;
#line 65
struct cleanup *make_cleanup(make_cleanup_ftype *function , void *arg ) ;
#line 68 "../include/common.h"
void discard_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 71
  discard_my_cleanups(& cleanup_chain, old_chain);
#line 72
  return;
}
}
#line 74 "../include/common.h"
void discard_final_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 77
  discard_my_cleanups(& final_cleanup_chain, old_chain);
#line 78
  return;
}
}
#line 80 "../include/common.h"
void discard_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) 
{ 
  struct cleanup *ptr ;

  {
#line 86
  while (1) {
#line 86
    ptr = *pmy_chain;
#line 86
    if (! ((unsigned long )ptr != (unsigned long )old_chain)) {
#line 86
      break;
    }
#line 88
    *pmy_chain = ptr->next;
#line 89
    if (ptr->free_arg) {
#line 90
      (*(ptr->free_arg))(ptr->arg);
    }
#line 91
    free((void *)ptr);
  }
#line 94
  printf((char const   * __restrict  )"freearg: %x\n", ptr->arg);
#line 95
  return;
}
}
#line 97 "../include/common.h"
static void do_my_cleanups(struct cleanup **pmy_chain , struct cleanup *old_chain ) 
{ 
  struct cleanup *ptr ;

  {
#line 103
  while (1) {
#line 103
    ptr = *pmy_chain;
#line 103
    if (! ((unsigned long )ptr != (unsigned long )old_chain)) {
#line 103
      break;
    }
#line 105
    *pmy_chain = ptr->next;
#line 106
    (*(ptr->function))(ptr->arg);
#line 107
    printf((char const   * __restrict  )"cleanup!!!!! =========\n");
#line 108
    printf((char const   * __restrict  )"%x\n", ptr->arg);
#line 109
    if (ptr->free_arg) {
#line 110
      (*(ptr->free_arg))(ptr->arg);
    }
#line 112
    free((void *)ptr);
  }
#line 114
  return;
}
}
#line 116 "../include/common.h"
void do_cleanups(struct cleanup *old_chain ) 
{ 


  {
#line 118
  do_my_cleanups(& cleanup_chain, old_chain);
#line 119
  return;
}
}
#line 121 "../include/common.h"
static struct cleanup *make_my_cleanup2(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                        void *arg , void (*free_arg)(void * ) ) 
{ 
  struct cleanup *new ;
  void *tmp ;
  struct cleanup *old_chain ;

  {
#line 125
  tmp = malloc(sizeof(struct cleanup ));
#line 125
  new = (struct cleanup *)tmp;
#line 127
  old_chain = *pmy_chain;
#line 129
  new->next = *pmy_chain;
#line 130
  new->function = function;
#line 131
  new->free_arg = free_arg;
#line 132
  new->arg = arg;
#line 133
  *pmy_chain = new;
#line 135
  if ((unsigned long )old_chain == (unsigned long )((void *)0)) {
#line 136
    exit(1);
  }
#line 138
  return (old_chain);
}
}
#line 141 "../include/common.h"
static struct cleanup *make_my_cleanup(struct cleanup **pmy_chain , make_cleanup_ftype *function ,
                                       void *arg ) 
{ 
  struct cleanup *tmp ;

  {
#line 145
  tmp = make_my_cleanup2(pmy_chain, function, arg, (void (*)(void * ))((void *)0));
#line 145
  return (tmp);
}
}
#line 148 "../include/common.h"
struct cleanup *make_cleanup(make_cleanup_ftype *function , void *arg ) 
{ 
  struct cleanup *tmp ;

  {
#line 151
  tmp = make_my_cleanup(& cleanup_chain, function, arg);
#line 151
  return (tmp);
}
}
#line 395 "../include/vec.h"
__inline static unsigned int calculate_allocation(struct vec_prefix  const  *pfx ,
                                                  int reserve ) 
{ 
  unsigned int alloc ;
  unsigned int num ;
  int tmp ;

  {
#line 398
  alloc = 0U;
#line 399
  num = 0U;
#line 401
  if (pfx) {
#line 403
    alloc = (unsigned int )pfx->alloc;
#line 404
    num = (unsigned int )pfx->num;
  } else
#line 406
  if (! reserve) {
#line 409
    return (0U);
  }
#line 412
  if (reserve < 0) {
#line 412
    tmp = - reserve;
  } else {
#line 412
    tmp = reserve;
  }
#line 412
  if (! (alloc - num < (unsigned int )tmp)) {
#line 413
    exit(1);
  }
#line 416
  if (reserve < 0) {
#line 418
    alloc = num + (unsigned int )(- reserve);
  } else {
#line 422
    if (! alloc) {
#line 423
      alloc = 4U;
    } else
#line 424
    if (alloc < 16U) {
#line 426
      alloc *= 2U;
    } else {
#line 429
      alloc = (alloc * 3U) / 2U;
    }
#line 432
    if (alloc < num + (unsigned int )reserve) {
#line 433
      alloc = num + (unsigned int )reserve;
    }
  }
#line 435
  return (alloc);
}
}
#line 439 "../include/vec.h"
void *vec_o_reserve(void *vec , int reserve , size_t vec_offset , size_t elt_size ) 
{ 
  struct vec_prefix *pfx ;
  unsigned int alloc ;
  unsigned int tmp ;

  {
#line 441
  pfx = (struct vec_prefix *)vec;
#line 442
  tmp = calculate_allocation((struct vec_prefix  const  *)pfx, reserve);
#line 442
  alloc = tmp;
#line 444
  if (! alloc) {
#line 445
    return ((void *)0);
  }
#line 447
  vec = realloc(vec, vec_offset + (size_t )alloc * elt_size);
#line 448
  if (! vec) {
#line 448
    exit(1);
  }
#line 450
  ((struct vec_prefix *)vec)->alloc = alloc;
#line 451
  if (! pfx) {
#line 452
    ((struct vec_prefix *)vec)->num = 0U;
  }
#line 454
  return (vec);
}
}
#line 27 "binutils_leak_6.c"
void null_cleanup(void *arg ) 
{ 


  {
#line 30
  return;
}
}
#line 32 "binutils_leak_6.c"
void *xrealloc(void *oldmem , size_t size ) 
{ 
  void *newmem ;

  {
#line 37
  if (size == 0UL) {
#line 38
    size = (size_t )1;
  }
#line 40
  newmem = realloc(oldmem, size);
#line 42
  if (! newmem) {
#line 43
    exit(1);
  }
#line 45
  return (newmem);
}
}
#line 108
extern int ( /* missing proto */  strcmp)() ;
#line 48 "binutils_leak_6.c"
static void add_symbol_file_command(char **args ) 
{ 
  int section_index ;
  int sec_num ;
  char *arg ;
  int expecting_sec_addr ;
  int expecting_sec_name ;
  int argcnt ;
  int i ;
  struct cleanup *my_cleanups ;
  struct cleanup *tmp ;
  struct section_addr_info *section_addrs ;
  struct sect_opt *sect_opts ;
  size_t num_sect_opts ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;
  int tmp___3 ;
  void *tmp___4 ;
  char const   *val ;
  char const   *sec ;

  {
#line 51
  section_index = 0;
#line 52
  sec_num = 0;
#line 54
  expecting_sec_addr = 0;
#line 55
  expecting_sec_name = 0;
#line 56
  argcnt = 0;
#line 59
  tmp = make_cleanup(& null_cleanup, (void *)0);
#line 59
  my_cleanups = tmp;
#line 62
  sect_opts = (struct sect_opt *)((void *)0);
#line 63
  num_sect_opts = (size_t )0;
#line 65
  num_sect_opts = (size_t )4;
#line 66
  tmp___0 = malloc(sizeof(struct sect_opt ) * num_sect_opts);
#line 66
  sect_opts = (struct sect_opt *)tmp___0;
#line 69
  if ((unsigned long )args == (unsigned long )((void *)0)) {
#line 69
    exit(1);
  }
#line 71
  arg = *(args + 0);
#line 71
  while ((unsigned long )arg != (unsigned long )((void *)0)) {
#line 73
    if (! (argcnt == 0)) {
#line 76
      if (argcnt == 1) {
#line 78
        (sect_opts + section_index)->name = ".text";
#line 79
        (sect_opts + section_index)->value = (char const   *)arg;
#line 80
        section_index ++;
#line 80
        if ((size_t )section_index >= num_sect_opts) {
#line 82
          num_sect_opts *= 2UL;
#line 83
          tmp___1 = xrealloc((void *)sect_opts, num_sect_opts * sizeof(struct sect_opt ));
#line 83
          sect_opts = (struct sect_opt *)tmp___1;
        }
      } else
#line 90
      if (expecting_sec_name) {
#line 92
        (sect_opts + section_index)->value = (char const   *)arg;
#line 93
        expecting_sec_addr = 0;
      } else
#line 95
      if (expecting_sec_addr) {
#line 97
        (sect_opts + section_index)->value = (char const   *)arg;
#line 98
        expecting_sec_addr = 0;
#line 100
        section_index ++;
#line 100
        if ((size_t )section_index >= num_sect_opts) {
#line 102
          num_sect_opts *= 2UL;
#line 103
          tmp___2 = xrealloc((void *)sect_opts, num_sect_opts * sizeof(struct sect_opt ));
#line 103
          sect_opts = (struct sect_opt *)tmp___2;
        }
      } else {
#line 108
        tmp___3 = strcmp(arg, "-s");
#line 108
        if (tmp___3 == 0) {
#line 110
          expecting_sec_name = 1;
#line 111
          expecting_sec_addr = 1;
        } else {
#line 114
          exit(1);
        }
      }
    }
    __Cont: /* CIL Label */ 
#line 71
    argcnt ++;
#line 71
    arg = *(args + argcnt);
  }
#line 118
  if (section_index < 1) {
#line 119
    exit(1);
  }
#line 121
  tmp___4 = malloc(sizeof(struct section_addr_info ));
#line 121
  section_addrs = (struct section_addr_info *)tmp___4;
#line 122
  make_cleanup((make_cleanup_ftype *)(& free), (void *)section_addrs);
#line 124
  i = 0;
#line 124
  while (i < section_index) {
#line 126
    val = (sect_opts + i)->value;
#line 127
    sec = (sect_opts + i)->name;
#line 131
    section_addrs->other[sec_num].name = (char *)sec;
#line 132
    sec_num ++;
#line 124
    i ++;
  }
#line 139
  section_addrs->num_sections = (size_t )sec_num;
#line 141
  do_cleanups(my_cleanups);
#line 143
  return;
}
}
#line 146 "binutils_leak_6.c"
int main(void) 
{ 
  char const   *args[6] ;

  {
#line 148
  args[0] = "prog";
#line 148
  args[1] = "v";
#line 148
  args[2] = "-s";
#line 148
  args[3] = "idx";
#line 148
  args[4] = "addr";
#line 148
  args[5] = (char const   *)((void *)0);
#line 149
  add_symbol_file_command((char **)(args));
#line 151
  return (0);
}
}
