/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 203 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef unsigned long u_int64_t;
#line 196 "../stdio.h"
typedef unsigned int u_int___0;
#line 200 "../stdio.h"
typedef int int32_t___0;
#line 207 "../stdio.h"
typedef unsigned char u_char___0;
#line 351 "../openssh.h"
struct sshbuf {
   u_char___0 *d ;
   u_char___0 const   *cd ;
   size_t off ;
   size_t size ;
   size_t max_size ;
   size_t alloc ;
   int readonly ;
   int dont_free ;
   u_int___0 refcount ;
   struct sshbuf *parent ;
};
#line 364 "../openssh.h"
typedef u_int___0 BN_ULONG;
#line 372 "../openssh.h"
struct bignum_st {
   BN_ULONG *d ;
   int top ;
   int dmax ;
   int neg ;
   int flags ;
};
#line 390 "../openssh.h"
typedef struct bignum_st BIGNUM;
#line 391 "../openssh.h"
struct rsa_st {
   int pad ;
   int32_t___0 version ;
   void const   *meth ;
   void *engine ;
   BIGNUM *n ;
   BIGNUM *e ;
   BIGNUM *d ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *dmp1 ;
   BIGNUM *dmq1 ;
   BIGNUM *iqmp ;
   void *pss ;
   int ex_data ;
   int references ;
   int flags ;
   void *_method_mod_n ;
   void *_method_mod_p ;
   void *_method_mod_q ;
   char *bignum_data ;
   void *blinding ;
   void *mt_blinding ;
   void *lock ;
};
#line 391 "../openssh.h"
typedef struct rsa_st RSA;
#line 434 "../openssh.h"
struct dsa_st {
   int pad ;
   int32_t___0 version ;
   BIGNUM *p ;
   BIGNUM *q ;
   BIGNUM *g ;
   BIGNUM *pub_key ;
   BIGNUM *priv_key ;
   int flags ;
};
#line 434 "../openssh.h"
typedef struct dsa_st DSA;
#line 626
struct sshkey;
#line 626 "../openssh.h"
struct sshkey_cert {
   struct sshbuf *certblob ;
   u_int___0 type ;
   u_int64_t serial ;
   char *key_id ;
   u_int___0 nprincipals ;
   char **principals ;
   u_int64_t valid_after ;
   u_int64_t valid_before ;
   struct sshbuf *critical ;
   struct sshbuf *extensions ;
   struct sshkey *signature_key ;
};
#line 640 "../openssh.h"
struct sshkey {
   int type ;
   int flags ;
   RSA *rsa ;
   DSA *dsa ;
   int ecdsa_nid ;
   void *ecdsa ;
   u_char___0 *ed25519_sk ;
   u_char___0 *ed25519_pk ;
   struct sshkey_cert *cert ;
};
#line 15 "openssh_df_1.c"
typedef void EVP_MD;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 374 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) rand)(void) ;
#line 376
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) srand)(unsigned int __seed ) ;
#line 466
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 468
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) calloc)(size_t __nmemb ,
                                                                               size_t __size )  __attribute__((__malloc__)) ;
#line 483
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 17 "openssh_df_1.c"
struct sshkey *sshkey_new(int type ) 
{ 
  struct sshkey *k ;
  DSA *dsa ;
  void *tmp ;
  void *tmp___0 ;

  {
#line 23
  tmp = calloc((size_t )1, sizeof(*k));
#line 23
  k = (struct sshkey *)tmp;
#line 23
  if ((unsigned long )k == (unsigned long )((void *)0)) {
#line 24
    return ((struct sshkey *)((void *)0));
  }
#line 25
  k->type = type;
#line 26
  k->ecdsa = (void *)0;
#line 27
  k->ecdsa_nid = -1;
#line 28
  k->dsa = (DSA *)((void *)0);
#line 29
  k->rsa = (RSA *)((void *)0);
#line 30
  k->cert = (struct sshkey_cert *)((void *)0);
#line 31
  k->ed25519_sk = (u_char___0 *)((void *)0);
#line 32
  k->ed25519_pk = (u_char___0 *)((void *)0);
#line 33
  switch (k->type) {
  case 6: 
  case 2: 
#line 36
  tmp___0 = malloc(sizeof(DSA ));
#line 36
  dsa = (DSA *)tmp___0;
#line 36
  if ((unsigned long )dsa == (unsigned long )((void *)0)) {
#line 37
    return ((struct sshkey *)((void *)0));
  }
#line 38
  k->dsa = dsa;
#line 39
  break;
  case 11: 
#line 41
  break;
  default: 
#line 43
  free((void *)k);
#line 44
  return ((struct sshkey *)((void *)0));
#line 45
  break;
  }
#line 47
  return (k);
}
}
#line 50 "openssh_df_1.c"
void sshkey_free(struct sshkey *k ) 
{ 


  {
#line 53
  if ((unsigned long )k == (unsigned long )((void *)0)) {
#line 54
    return;
  }
#line 55
  switch (k->type) {
  case 6: 
  case 2: 
#line 58
  if ((unsigned long )k->dsa != (unsigned long )((void *)0)) {
#line 59
    free((void *)k->dsa);
  }
#line 60
  k->dsa = (DSA *)((void *)0);
#line 61
  break;
  default: 
#line 63
  break;
  }
#line 65
  free((void *)k);
#line 66
  return;
}
}
#line 68 "openssh_df_1.c"
int dsa_builtin_paramgen(DSA *ret ) 
{ 
  int ok ;
  int tmp___0 ;

  {
#line 70
  ok = 0;
#line 72
  printf((char const   * __restrict  )"%d\n", ret);
#line 73
  if ((unsigned long )ret->p == (unsigned long )((void *)0)) {
#line 73
    goto _L;
  } else
#line 73
  if ((unsigned long )ret->q == (unsigned long )((void *)0)) {
#line 73
    goto _L;
  } else
#line 73
  if ((unsigned long )ret->g == (unsigned long )((void *)0)) {
    _L: /* CIL Label */ 
#line 74
    tmp___0 = rand();
#line 74
    if (tmp___0 % 2 == 1) {
#line 74
      ok = 1;
    } else {
#line 74
      ok = 0;
    }
  }
#line 76
  return (ok);
}
}
#line 79 "openssh_df_1.c"
int DSA_generate_parameters_ex(DSA *ret ) 
{ 
  size_t qbits ;
  int tmp ;

  {
#line 82
  qbits = (size_t )8;
#line 84
  tmp = dsa_builtin_paramgen(ret);
#line 84
  return (tmp);
}
}
#line 88 "openssh_df_1.c"
static int dsa_generate_private_key(u_int___0 bits , DSA **dsap ) 
{ 
  DSA *private ;
  int ret ;
  void *tmp ;
  int tmp___0 ;

  {
#line 92
  ret = -1;
#line 94
  if ((unsigned long )dsap == (unsigned long )((void *)0)) {
#line 95
    return (-10);
  }
#line 96
  tmp = malloc(sizeof(DSA ));
#line 96
  private = (DSA *)tmp;
#line 96
  if ((unsigned long )private == (unsigned long )((void *)0)) {
#line 97
    ret = -2;
#line 98
    goto out;
  }
#line 100
  *dsap = (DSA *)((void *)0);
#line 101
  tmp___0 = DSA_generate_parameters_ex(private);
#line 101
  if (! tmp___0) {
#line 102
    free((void *)private);
#line 103
    ret = -22;
#line 104
    goto out;
  }
#line 106
  *dsap = private;
#line 107
  private = (DSA *)((void *)0);
#line 108
  ret = 0;
  out: 
#line 110
  if ((unsigned long )private != (unsigned long )((void *)0)) {
#line 111
    free((void *)private);
  }
#line 112
  return (ret);
}
}
#line 115 "openssh_df_1.c"
int sshkey_generate(int type , u_int___0 bits , struct sshkey **keyp ) 
{ 
  struct sshkey *k ;
  int ret ;

  {
#line 119
  ret = -1;
#line 121
  if ((unsigned long )keyp == (unsigned long )((void *)0)) {
#line 122
    return (-10);
  }
#line 123
  *keyp = (struct sshkey *)((void *)0);
#line 124
  k = sshkey_new(11);
#line 124
  if ((unsigned long )k == (unsigned long )((void *)0)) {
#line 125
    return (-2);
  }
#line 126
  switch (type) {
  case 2: 
#line 128
  ret = dsa_generate_private_key(bits, & k->dsa);
#line 129
  break;
  default: 
#line 131
  ret = -10;
  }
#line 133
  if (ret == 0) {
#line 134
    k->type = type;
#line 135
    *keyp = k;
  } else {
#line 137
    sshkey_free(k);
  }
#line 138
  return (ret);
}
}
#line 145
extern int ( /* missing proto */  time)() ;
#line 141 "openssh_df_1.c"
int main(void) 
{ 
  u_int___0 bits ;
  struct sshkey *private ;
  int tmp ;
  int tmp___0 ;

  {
#line 145
  tmp = time((void *)0);
#line 145
  srand((unsigned int )tmp);
#line 146
  tmp___0 = sshkey_generate(2, bits, & private);
#line 146
  if (tmp___0) {
#line 147
    printf((char const   * __restrict  )"sshkey_generate error%s\n", "");
#line 147
    exit(1);
  }
#line 148
  (private->dsa)->flags = 0;
#line 149
  sshkey_free(private);
#line 150
  return (0);
}
}
